<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analytics 102 -- Applied Statistics and Regression Using R – ztests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analytics 102 – Applied Statistics and Regression Using R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Sameer Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Aryeman Gupta Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/SameerMathur/DataAnalytics102" rel="" target="_blank"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Book’s Github</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02ZTests.html">Z Tests</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/openscapes_hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01GettingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02ZTests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Z Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03ChiSquareTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chi-Square Tests</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="BookCover102.png" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#z-tests" id="toc-z-tests" class="nav-link active" data-scroll-target="#z-tests">Z Tests</a>
  <ul class="collapse">
  <li><a href="#overview-of-z-tests" id="toc-overview-of-z-tests" class="nav-link" data-scroll-target="#overview-of-z-tests">Overview of Z Tests</a></li>
  <li><a href="#business-applications-of-z-tests-for-categorical-data" id="toc-business-applications-of-z-tests-for-categorical-data" class="nav-link" data-scroll-target="#business-applications-of-z-tests-for-categorical-data">Business Applications of Z Tests for Categorical Data</a>
  <ul class="collapse">
  <li><a href="#marketing" id="toc-marketing" class="nav-link" data-scroll-target="#marketing">Marketing</a></li>
  <li><a href="#finance" id="toc-finance" class="nav-link" data-scroll-target="#finance">Finance</a></li>
  <li><a href="#organizational-behavior" id="toc-organizational-behavior" class="nav-link" data-scroll-target="#organizational-behavior">Organizational Behavior:</a></li>
  </ul></li>
  <li><a href="#one-sample-z-test-for-proportions" id="toc-one-sample-z-test-for-proportions" class="nav-link" data-scroll-target="#one-sample-z-test-for-proportions">One-sample Z-test for Proportions</a>
  <ul class="collapse">
  <li><a href="#one-sample-z-test-for-proportions---concepts" id="toc-one-sample-z-test-for-proportions---concepts" class="nav-link" data-scroll-target="#one-sample-z-test-for-proportions---concepts">One-sample Z-test for Proportions - Concepts</a></li>
  <li><a href="#numerical-example-for-one-sample-z-test-for-proportions" id="toc-numerical-example-for-one-sample-z-test-for-proportions" class="nav-link" data-scroll-target="#numerical-example-for-one-sample-z-test-for-proportions">Numerical Example for One-sample Z-test for Proportions</a></li>
  <li><a href="#running-one-sample-z-test-for-proportions-in-r" id="toc-running-one-sample-z-test-for-proportions-in-r" class="nav-link" data-scroll-target="#running-one-sample-z-test-for-proportions-in-r">Running One-sample Z-test for Proportions in R</a></li>
  </ul></li>
  <li><a href="#independent-samples-z-test-for-proportions" id="toc-independent-samples-z-test-for-proportions" class="nav-link" data-scroll-target="#independent-samples-z-test-for-proportions">Independent samples Z-test for Proportions</a>
  <ul class="collapse">
  <li><a href="#independent-samples-z-test-for-proportions---concepts" id="toc-independent-samples-z-test-for-proportions---concepts" class="nav-link" data-scroll-target="#independent-samples-z-test-for-proportions---concepts">Independent samples Z-test for Proportions - Concepts</a></li>
  <li><a href="#numerical-example-for-independent-samples-z-test" id="toc-numerical-example-for-independent-samples-z-test" class="nav-link" data-scroll-target="#numerical-example-for-independent-samples-z-test">Numerical Example for Independent samples Z-test</a></li>
  <li><a href="#running-independent-samples-z-test-in-r" id="toc-running-independent-samples-z-test-in-r" class="nav-link" data-scroll-target="#running-independent-samples-z-test-in-r">Running Independent samples Z-test in R</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="02ZTests.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="z-tests" class="level1">
<h1>Z Tests</h1>
<p><em>July 26, 2023</em></p>
<section id="overview-of-z-tests" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-z-tests">Overview of Z Tests</h2>
<p>Depending on the research question and the type of data being analyzed, different types of Z-tests are frequently employed in statistics.</p>
<p>Variations of the Z-test can be used to compare sample means or sample proportions. In this tutorial, we will confine our attention to the Z-tests used to analyze categorical data and sample proportions.</p>
<p>The following are three prevalent types of Z-tests for Categorical data:</p>
<ol type="1">
<li><p><strong>One-sample Z-test:</strong> This test determines whether a sample mean or proportion significantly deviates from a known or hypothesized population mean or proportion.</p></li>
<li><p><strong>Two-sample Z-test:</strong> This test is used to determine whether there is a statistically significant difference between the means or proportions of two independent groups.</p></li>
<li><p><strong>Paired Z-test for proportions:</strong> This test determines whether there is a statistically significant difference in proportions between two related groups, such as before and after a treatment or intervention. [1]</p></li>
</ol>
</section>
<section id="business-applications-of-z-tests-for-categorical-data" class="level2">
<h2 class="anchored" data-anchor-id="business-applications-of-z-tests-for-categorical-data">Business Applications of Z Tests for Categorical Data</h2>
<section id="marketing" class="level3">
<h3 class="anchored" data-anchor-id="marketing">Marketing</h3>
<p>In marketing research and analysis, Z-tests for categorical data are useful tools for testing hypotheses and determining the significance of relationships between categorical variables. Here are some possible marketing applications of Z-tests for categorical data:</p>
<ol type="1">
<li><p><strong>Brand loyalty:</strong> A marketer may wish to determine whether customers who purchase a particular brand are more loyal to the brand than those who purchase a competing brand. To compare the proportion of loyal customers between the two brands, a two-sample Z-test for proportions could be utilized.</p></li>
<li><p><strong>Customer satisfaction:</strong> A marketer may wish to determine whether a new product or service is more satisfying to customers than its predecessor. Before and after the introduction of the new product or service, the proportion of satisfied customers could be compared using McNemar’s test.</p></li>
<li><p><strong>Market segmentation:</strong> A marketer may use market segmentation to determine whether there are significant differences in customer demographics or behavior across market segments. A Chi-square test could be utilized to determine if there is a significant relationship between the demographic variables and market segments.</p></li>
<li><p><strong>Advertising effectiveness:</strong> A marketer may wish to determine if one advertising campaign is more effective than another at reaching the target audience. A two-sample Z-test for proportions could be used to compare the proportion of viewers who remember the message or take action following exposure to each campaign.</p></li>
<li><p><strong>Product preference:</strong> A marketer may wish to determine whether a particular product feature or characteristic is more preferred by customers than another. A one-sample Z-test for proportions could be utilized to determine if the proportion of customers who prefer the feature significantly deviates from the null hypothesis. [2]</p></li>
</ol>
</section>
<section id="finance" class="level3">
<h3 class="anchored" data-anchor-id="finance">Finance</h3>
<p>Z tests can be helpful in studying different aspects of Finance such as default rates, investment decisions, stock market analysis, risk analysis.</p>
<ol type="1">
<li><p><strong>Credit risk assessment:</strong> A financial institution assessing credit risk may wish to determine whether the proportion of delinquent loans varies significantly across risk categories. A two-sample Z-test for proportions could be utilized to compare the proportion of delinquent loans across various risk categories.</p></li>
<li><p><strong>Investment portfolio analysis:</strong> An investor may wish to determine whether the proportion of winning trades varies significantly between different types of investments, including stocks, bonds, and commodities. Using a two-sample Z-test for proportions, it is possible to compare the proportion of profitable trades for the various types of investments.</p></li>
<li><p><strong>Customer behavior analysis:</strong> A financial institution may conduct an analysis of customer behavior to determine whether the proportion of customers who use online banking varies significantly by age group. A Chi-square test could be utilized to determine if there is a significant relationship between the demographic variable (age group) and the proportion of customers who use online banking.</p></li>
<li><p><strong>Market analysis:</strong> An investment bank may wish to determine if there is a significant correlation between the market type (bullish or bearish) and the proportion of investors who sell or purchase stocks. A Chi-square test could be used to determine if there is a significant relationship between the type of market and the proportion of investors who sell or purchase stocks.</p></li>
<li><p><strong>Fraud detection:</strong> A financial institution may wish to determine whether the proportion of fraudulent transactions varies significantly between different types of transactions, such as ATM withdrawals, online purchases, and wire transfers, for the purpose of detecting fraud. A one-sample Z-test for proportions could be used to determine if the proportion of fraudulent transactions in a specific type of transaction significantly deviates from a null hypothesis. [3]</p></li>
</ol>
</section>
<section id="organizational-behavior" class="level3">
<h3 class="anchored" data-anchor-id="organizational-behavior">Organizational Behavior:</h3>
<p>In organizational behavior research, Z-tests for categorical data can be useful tools for analyzing data and making informed decisions. Here are some potential organizational behavior applications of Z-tests for categorical data:</p>
<ol type="1">
<li><p><strong>Employee satisfaction:</strong> An organization may wish to determine whether the proportion of satisfied employees varies significantly across departments. Using a two-sample Z-test for proportions, it is possible to compare the percentage of satisfied employees across departments.</p></li>
<li><p><strong>Diversity and inclusion:</strong> An organization may wish to determine whether the proportion of employees from diverse backgrounds varies significantly across management levels. A Chi-square test could be used to determine whether there is a significant relationship between the demographic variable (race, gender, etc.) and the management level.</p></li>
<li><p><strong>Employee engagement:</strong> An organization may wish to determine whether the proportion of engaged employees differs significantly across teams or work units. Using a two-sample Z-test for proportions, it is possible to compare the proportion of engaged employees among various teams or work units.</p></li>
<li><p><strong>Training effectiveness:</strong> An organization may wish to determine whether the percentage of employees who pass a certification exam differs significantly between those who have completed a training program and those who have not. The proportion of employees who pass the certification exam could be compared between the two groups using a two-sample Z-test for proportions.</p></li>
<li><p><strong>Employee turnover:</strong> An organization may wish to determine whether the proportion of employees who voluntarily leave the organization varies significantly across job functions or departments. A Chi-square test could be used to determine whether there is a significant relationship between the job function or department and the percentage of employees who leave the organization voluntarily. [4]</p></li>
</ol>
</section>
</section>
<section id="one-sample-z-test-for-proportions" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-z-test-for-proportions">One-sample Z-test for Proportions</h2>
<ol type="1">
<li><p>This type of Z-test is used to examine a population proportion hypothesis.</p></li>
<li><p>For instance, a business may wish to determine whether the proportion of customers who are satisfied with their product exceeds 0.5.</p></li>
<li><p>The company could collect a sample of customers, determine the proportion of satisfied customers in the sample, and use a one-sample Z-test to determine if the proportion is significantly different from 0.5.</p></li>
</ol>
<section id="one-sample-z-test-for-proportions---concepts" class="level3">
<h3 class="anchored" data-anchor-id="one-sample-z-test-for-proportions---concepts">One-sample Z-test for Proportions - Concepts</h3>
<ol type="1">
<li><p>The general steps to perform a one-sample Z-test are:</p>
<ol type="1">
<li><p><strong>State the null hypothesis and alternative hypothesis:</strong> Typically, the null hypothesis states that the sample proportion matches the hypothesized population proportion, whereas the alternative hypothesis states that the sample proportion differs from the hypothesized population proportion.</p></li>
<li><p><strong>Determine the level of significance (α):</strong> This is the maximum probability of rejecting the null hypothesis when it is true. Typical values for α are 0.05 or 0.01.</p></li>
<li><p><strong>Collect sample data:</strong> Obtain a random sample from the population and calculate the sample proportion (p).</p></li>
<li><p><strong>Calculate the test statistic:</strong> The test statistic is calculated as follows: <span class="math inline">\(z = (p - p_0) / \sqrt(p_0 * (1 - p_0) / n)\)</span> , where <span class="math inline">\(p_0\)</span> is the population proportion assumed under the null hypothesis, and <span class="math inline">\(n\)</span> is the sample size.</p></li>
<li><p><strong>Determine the critical value:</strong> The critical value is the value of <span class="math inline">\(z\)</span> that corresponds to the chosen level of significance and degrees of freedom (df = n-1).</p></li>
<li><p><strong>Compare the test statistic to the critical value:</strong> If the absolute value of the test statistic is greater than the critical value, we reject the null hypothesis. Otherwise, we fail to reject the null hypothesis.</p></li>
<li><p><strong>Interpret the results:</strong> If the null hypothesis is rejected, one can conclude that the proportion of the sample is significantly different from that of the population. If the null hypothesis is not rejected, it can be concluded that the sample proportion is not significantly different from the population proportion.</p></li>
<li><p><strong>Determine the p-value</strong> using a Z-table or calculator, and compare the p-value to the level of significance (alpha) in order to reach a conclusion.</p></li>
<li><p><strong>Draw a conclusion.</strong> [5]</p></li>
</ol></li>
</ol>
</section>
<section id="numerical-example-for-one-sample-z-test-for-proportions" class="level3">
<h3 class="anchored" data-anchor-id="numerical-example-for-one-sample-z-test-for-proportions">Numerical Example for One-sample Z-test for Proportions</h3>
<ol type="1">
<li><p>Suppose a researcher wishes to determine whether the proportion of adults in a population who own a car significantly deviates from the null hypothesis of 70%. A random sample of 200 adults reveals that 150 of them own smartphones.</p></li>
<li><p>The null hypothesis states that the sample proportion equals the population proportion, whereas the alternative hypothesis states that the sample proportion does not equal the population proportion.</p>
<ul>
<li><p>H0: p = 0.7</p></li>
<li><p>Ha: p ≠ 0.7</p></li>
</ul>
<p>where p is the proportion of the population.</p></li>
<li><p>Next, we establish the <strong>significance level</strong>, which is typically set at 0.05.</p></li>
<li><p>The <strong>critical value</strong> for a two-tailed test with a significance level of 0.05 is 1.96.</p></li>
<li><p>Now we can calculate the <strong>test statistic</strong> with the following formula:</p>
<p>Z = (p - P) / sqrt(P * (1 - P) / n)</p>
<p>where P is the hypothesized proportion of the population, p is the proportion of the sample, and n is the sample size.</p></li>
<li><p>Z = (0.75 - 0.7) / sqrt(0.7 * (1 - 0.7) / 200)</p>
<p>Z = 1.76</p></li>
<li><p>Since the absolute value of the test statistic is greater than the critical value (1.76 &gt; 1.96), we reject the null hypothesis and conclude that the sample proportion of 0.75 differs significantly from the expected population proportion of 0.70.</p></li>
<li><p>Therefore, we can conclude with 95% assurance that the proportion of adults who own a smartphone in the population is significantly different from 70%. [6]</p></li>
</ol>
</section>
<section id="running-one-sample-z-test-for-proportions-in-r" class="level3">
<h3 class="anchored" data-anchor-id="running-one-sample-z-test-for-proportions-in-r">Running One-sample Z-test for Proportions in R</h3>
<ol type="1">
<li>Suppose we want to test whether the proportion of cars with a 6-cylinder engine is significantly different from a hypothesized value of 50%.</li>
</ol>
<ul>
<li><p>Null hypothesis: The proportion of 6-cylinder engine cars in the <code>mtcars</code> dataset is 0.5 (p = 0.5).</p></li>
<li><p>Alternative hypothesis: The proportion of 6-cylinder engine cars in the <code>mtcars</code> dataset is not equal to 0.5 (p ≠ 0.5).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a binary variable indicating whether a car has a 6-cylinder engine or not</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>is_cyl6 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(mtcars<span class="sc">$</span>cyl <span class="sc">==</span> <span class="dv">6</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of 6 cylinder cars</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n6 <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>is_cyl6)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the total number of cars</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(mtcars<span class="sc">$</span>is_cyl6)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># alternate code</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n &lt;- nrow(mtcars)</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample proportion of cars with a 6-cylinder engine</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>prop_cyl6 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>is_cyl6)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct a one-sample Z-test for proportions using the prop.test function</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(n6, </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>          n, </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">p =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  n6 out of n, null probability 0.5
X-squared = 9.0312, df = 1, p-value = 0.002654
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.09944097 0.40441815
sample estimates:
      p 
0.21875 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>The sample proportion is 0.21875, indicating that only 21.9% of the cars in the dataset are equipped with a six-cylinder engine.</li>
<li>Using the prop.test function, we can now perform a one-sample Z-test on proportions:</li>
<li>The prop.test function requires three arguments: the number of successes (in this case, the number of cars with a 6-cylinder engine), the total number of trials (in this case, the total number of cars), and the population proportion hypothesis (0.5 in this case).</li>
<li>The output reveals that the test statistic is X-squared = 9.0312 with a p-value of 0.002654 and one degree of freedom.</li>
<li>Since the p-value is less than the significance level (0.05), we reject the null hypothesis and conclude that the proportion of cars in the population with a 6-cylinder engine is significantly different from 50%.</li>
<li>The sample proportion estimate is 0.219%, with a 95% confidence interval encompassing this value (0.099, 0.404). [7]</li>
</ol>
</section>
</section>
<section id="independent-samples-z-test-for-proportions" class="level2">
<h2 class="anchored" data-anchor-id="independent-samples-z-test-for-proportions">Independent samples Z-test for Proportions</h2>
<ol type="1">
<li><p>The independent samples Z-test for proportions is a statistical test used to determine if there is a statistically significant difference between two sample proportions drawn from independent populations.</p></li>
<li><p>A company may wish to determine, for instance, whether the proportion of male customers who purchase their product differs significantly from the proportion of female customers who purchase their product.</p></li>
<li><p>The company could collect separate samples of male and female customers, calculate the proportion of customers in each sample who purchased the product, and use a Z-test for independent samples to determine whether the difference in proportions is statistically significant. [8]</p></li>
</ol>
<section id="independent-samples-z-test-for-proportions---concepts" class="level3">
<h3 class="anchored" data-anchor-id="independent-samples-z-test-for-proportions---concepts">Independent samples Z-test for Proportions - Concepts</h3>
<p>Here are the steps involved in conducting an independent samples&nbsp;Z-test for proportions:</p>
<ol type="1">
<li><p><strong>State the null and alternative hypotheses:</strong> The null hypothesis asserts that the two population proportions are equal, while the alternative hypothesis asserts that they are not.</p></li>
<li><p><strong>Determine the level of significance.</strong> This is the level of risk the researcher is willing to accept when deciding on the null hypothesis. Typically, the significance level is set at 0.05.</p></li>
<li><p><strong>Determine the test’s statistic:</strong> The test statistic for a Z-test for proportions using independent samples is calculated using the following formula.</p>
<p>Z = (p1 - p2) / sqrt(p * (1 - p) * (1 / n1 + 1 / n2))</p>
<p>where p1 and p2 are sample proportions, n1 and n2 are sample sizes, and p is the pooled sample proportion, which is calculated as follows:</p>
<p>p = (x1 + x2) / (n1 + n2)</p>
<p>where x1 and x2 represent the success rate of each sample.</p>
<p>The <strong>critical value</strong> is the value of the test statistic that corresponds to the level of significance and the degrees of freedom.</p></li>
<li><p><strong>Comparing the test statistic to the threshold:</strong> The null hypothesis is rejected if the absolute value of the test statistic is greater than the critical value. If not, the null hypothesis cannot be rejected.</p></li>
<li><p>On the basis of the test results, the researcher can draw a conclusion regarding whether the two population proportions differ significantly. [8]</p></li>
</ol>
</section>
<section id="numerical-example-for-independent-samples-z-test" class="level3">
<h3 class="anchored" data-anchor-id="numerical-example-for-independent-samples-z-test">Numerical Example for Independent samples Z-test</h3>
<ol type="1">
<li><p>Suppose a researcher is interested in comparing the proportion of men and women who purchase a particular product. A random sample of 200 men and 300 women reveals that 100 men and 150 women bought the product.</p></li>
<li><p>The null hypothesis states that the proportion of men and women who purchase the product is equal, whereas the alternative hypothesis states that the proportion is not equal. Hence, we have:</p>
<ul>
<li><p>H0: p1 = p2</p></li>
<li><p>Ha: p1 ≠ p2</p></li>
</ul>
<p>where p1 represents the percentage of men who buy the product and p2 represents the percentage of women who buy the product.</p></li>
<li><p>Next, we establish the significance level, which is typically set at 0.05.</p></li>
<li><p>1.96 is the critical value for a two-tailed test with a significance level of 0.05.</p></li>
<li><p>Now we can calculate the test statistic with the following formula:</p>
<p>Z = (p1 - p2) / sqrt(p * (1 - p) * (1 / n1 + 1 / n2))</p>
<p>where p is the proportion of the pooled sample calculated as:</p>
<p>p = (x1 + x2) / (n1 + n2)</p>
<p>where x1 and x2 represent the success rates for each sample and n1 and n2 represent the sample sizes.</p></li>
<li><p>Using the data provided, we have:</p>
<p>p1 = 100 / 200 = 0.5</p>
<p>p2 = 150 / 300 = 0.5</p>
<p>n1 = 200</p>
<p>p = (100 + 150) / (200 + 300) = 0.4167</p></li>
<li><p>The test statistic is thus:</p>
<p>Z = (0.5 - 0.5) / sqrt(0.4167 * (1 - 0.4167) * (1 / 200 + 1 / 300)) = 0</p></li>
<li><p>Due to the fact that the absolute value of the test statistic is less than the critical value (|0| &lt;&nbsp;1.96), we fail to reject&nbsp;the null hypothesis and conclude that there is insufficient evidence to suggest that the proportion of men and women who purchase the product differs.</p></li>
<li><p>Therefore, we can conclude with 95%&nbsp;level of confidence that the proportion of men and women who purchase the product does not differ significantly.</p></li>
</ol>
</section>
<section id="running-independent-samples-z-test-in-r" class="level3">
<h3 class="anchored" data-anchor-id="running-independent-samples-z-test-in-r">Running Independent samples Z-test in R</h3>
<ol type="1">
<li>Suppose we wish to compare the proportion of cars in the mtcars dataset with automatic transmission (am = 1) to those with V-shaped engines (vs = 1).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create two vectors representing the two samples</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>sample1 <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>am <span class="co"># Sample 1: cars with automatic transmission</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>sample2 <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>vs <span class="co"># Sample 2: cars with v-shaped engines</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct a two-sample test for equality of proportions</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fu">sum</span>(sample1 <span class="sc">==</span> <span class="dv">1</span>), <span class="fu">sum</span>(sample2 <span class="sc">==</span> <span class="dv">1</span>)),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="fu">c</span>(<span class="fu">length</span>(sample1), <span class="fu">length</span>(sample2)),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(sum(sample1 == 1), sum(sample2 == 1)) out of c(length(sample1), length(sample2))
X-squared = 0, df = 1, p-value = 1
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.3043652  0.2418652
sample estimates:
 prop 1  prop 2 
0.40625 0.43750 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>The code generates two vectors, sample1 and sample2, representing the two samples for which the proportion of successes is to be compared.</li>
<li>In this example, sample1 represents the percentage of automobiles with automatic transmission (am = 1) and sample2 represents the percentage of automobiles with V-shaped engines (vs = 1).</li>
<li>The final code block uses the prop.test() function to conduct a two-sample test for proportional equality. x is a vector of the counts of successes (cars with automatic transmission or cars with v-shaped engines) for each sample, while n is a vector of the total number of trials (the total number of cars) for each sample.</li>
<li>The alternative argument specifies the two-sidedness of the alternative hypothesis.</li>
<li>The function prop.test() returns the test statistic, degrees of freedom, p-value, and confidence interval as its output.</li>
<li>The null hypothesis states that the proportion of automobiles with automatic transmissions and those with V-shaped engines are equal. If the p-value is less than the significance level (typically 0.05), we can reject the null hypothesis and conclude that the proportions of successes in the two samples differ significantly.</li>
<li>The output includes the test name (Two-sample test for equality of proportions with continuity correction), the sample proportions (prop 1 and prop 2), the test statistic (X-squared), the degrees of freedom (df), the p-value (p-value), the alternative hypothesis, and the 95% confidence interval (95 percent confidence interval).</li>
<li>In this instance, the p-value is less than 0.05, indicating that we can reject the null hypothesis of equal proportions and conclude that the proportions of cars with automatic transmission and V-shaped engines are significantly different.</li>
<li>The sample proportion estimates for am and vs are respectively 0.666667 and 0.1250000. The 95% confidence interval for the difference in proportions is (0.09437123, 0.31162877), which indicates that we are 95% confident that the true&nbsp;difference in proportions&nbsp;lies within this interval. [8]</li>
</ol>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>[1]</p>
<p>Agresti, A. (2002). Categorical data analysis (2nd ed.). Wiley.</p>
<p>[2]</p>
<p>Hair Jr, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2010). Multivariate data analysis: A global perspective (7th ed.). Pearson Education.</p>
<p>Churchill Jr, G. A., &amp; Iacobucci, D. (2010). Marketing research: Methodological foundations (10th ed.). Cengage Learning.</p>
<p>Kotler, P., &amp; Keller, K. L. (2012). Marketing management (14th ed.). Pearson Education.</p>
<p>Babin, B. J., &amp; Zikmund, W. G. (2016). Essentials of marketing research (5th ed.). Cengage Learning.</p>
<p>Malhotra, N. K., &amp; Peterson, M. (2006). Basic marketing research (3rd ed.). Prentice-Hall.</p>
<p>[3]</p>
<p>Altman, E. I. (2008). Evaluating credit risk models. Journal of Banking &amp; Finance, 32(8), 1544-1558.</p>
<p>Nofsinger, J. R. (2012). The psychology of investing (5th ed.). Pearson Education.</p>
<p>Mitra, A., &amp; Gilbert, T. (2012). Banking on customer knowledge: The potential of customer relationship management and analytics in retail banking. Journal of Service Research, 15(1), 59-75.</p>
<p>French, K. R., Schwert, G. W., &amp; Stambaugh, R. F. (1987). Expected stock returns and volatility. Journal of Financial Economics, 19(1), 3-29.</p>
<p>Tsay, R. S., &amp; Chen, T. H. (2012). Financial time series analysis (2nd ed.). Wiley.</p>
<p>[4]</p>
<p>Judge, T. A., &amp; Watanabe, S. (1994). Another look at the job satisfaction-life satisfaction relationship. Journal of Applied Psychology, 79(6), 939-948.</p>
<p>Roberson, Q. M. (2019). Race and ethnicity in the workplace. Annual Review of Organizational Psychology and Organizational Behavior, 6, 413-438.</p>
<p>Saks, A. M. (2006). Antecedents and consequences of employee engagement. Journal of Managerial Psychology, 21(7), 600-619.</p>
<p>Phillips, J. J. (2016). Handbook of training evaluation and measurement methods (4th ed.). Routledge.</p>
<p>Mobley, W. H., Horner, S. O., &amp; Hollingsworth, A. T. (1978). An evaluation of precursors of hospital employee turnover. Journal of Applied Psychology, 63(4), 408-414.</p>
<p>[5]</p>
<p>Arsham, H. (2019). Statistical thinking for management (2nd ed.). Prentice-Hall.</p>
<p>Hogg, R. V., McKean, J. W., &amp; Craig, A. T. (2019). Introduction to mathematical statistics (8th ed.). Pearson Education.</p>
<p>Sullivan, L. M., &amp; Artino Jr, A. R. (2013). Analyzing and interpreting data from Likert-type scales. Journal of Graduate Medical Education, 5(4), 541-542.</p>
<p>[6]</p>
<p>Arsham, H. (2019). Statistical thinking for management (2nd ed.). Prentice-Hall.</p>
<p>Hogg, R. V., McKean, J. W., &amp; Craig, A. T. (2019). Introduction to mathematical statistics (8th ed.). Pearson Education.</p>
<p>[7]</p>
<p>Venables, W. N., &amp; Ripley, B. D. (2002). Modern applied statistics with S (4th ed.). Springer.</p>
<p>R Core Team. (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. <a href="https://www.r-project.org/"><strong>https://www.R-project.org/</strong></a></p>
<p>[8]</p>
<p>Arsham, H. (2019). Statistical thinking for management (2nd ed.). Prentice-Hall.</p>
<p>Hogg, R. V., McKean, J. W., &amp; Craig, A. T. (2019). Introduction to mathematical statistics (8th ed.). Pearson Education.</p>
<p>Kirk, R. E. (2013). Experimental design: Procedures for the behavioral sciences (4th ed.). Sage.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/">Sameer Mathur</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true">Aryeman Gupta Mathur</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>