<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analytics 102 -- Applied Statistics and Regression Using R – linearregression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analytics 102 – Applied Statistics and Regression Using R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Sameer Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Aryeman Gupta Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/SameerMathur/DataAnalytics102" rel="" target="_blank"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Book’s Github</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07LinearRegression.html">Linear Regression.</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/openscapes_hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01GettingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02ZTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Z Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03ChiSquareTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chi-Square Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04TTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07LinearRegression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Linear Regression.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09LogLinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Log-Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10LogLog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Log-Log Regression</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="BookCover102.png" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#linear-regression." id="toc-linear-regression." class="nav-link active" data-scroll-target="#linear-regression.">Linear Regression.</a>
  <ul class="collapse">
  <li><a href="#business-applications-of-linear-regression" id="toc-business-applications-of-linear-regression" class="nav-link" data-scroll-target="#business-applications-of-linear-regression">Business Applications of Linear Regression</a>
  <ul class="collapse">
  <li><a href="#marketing" id="toc-marketing" class="nav-link" data-scroll-target="#marketing">Marketing</a></li>
  <li><a href="#finance" id="toc-finance" class="nav-link" data-scroll-target="#finance">Finance</a></li>
  <li><a href="#organizational-behavior" id="toc-organizational-behavior" class="nav-link" data-scroll-target="#organizational-behavior">Organizational Behavior</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#model-of-simple-linear-regression" id="toc-model-of-simple-linear-regression" class="nav-link" data-scroll-target="#model-of-simple-linear-regression">Model of Simple Linear Regression</a></li>
  <li><a href="#running-simple-linear-regression-in-r" id="toc-running-simple-linear-regression-in-r" class="nav-link" data-scroll-target="#running-simple-linear-regression-in-r">Running Simple Linear Regression in R</a>
  <ul class="collapse">
  <li><a href="#goal" id="toc-goal" class="nav-link" data-scroll-target="#goal">Goal</a></li>
  <li><a href="#steps" id="toc-steps" class="nav-link" data-scroll-target="#steps">Steps</a></li>
  </ul></li>
  <li><a href="#visualizing-simple-linear-regression-in-r" id="toc-visualizing-simple-linear-regression-in-r" class="nav-link" data-scroll-target="#visualizing-simple-linear-regression-in-r">Visualizing Simple Linear Regression in R</a>
  <ul class="collapse">
  <li><a href="#goal-1" id="toc-goal-1" class="nav-link" data-scroll-target="#goal-1">Goal</a></li>
  <li><a href="#steps-1" id="toc-steps-1" class="nav-link" data-scroll-target="#steps-1">Steps</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#overview-1" id="toc-overview-1" class="nav-link" data-scroll-target="#overview-1">Overview</a></li>
  <li><a href="#model-of-multiple-linear-regression" id="toc-model-of-multiple-linear-regression" class="nav-link" data-scroll-target="#model-of-multiple-linear-regression">Model of Multiple Linear Regression</a></li>
  <li><a href="#ordinary-least-squares-ols-estimation" id="toc-ordinary-least-squares-ols-estimation" class="nav-link" data-scroll-target="#ordinary-least-squares-ols-estimation">Ordinary Least Squares (OLS) Estimation</a></li>
  <li><a href="#running-multiple-linear-regression-using-ols-in-r" id="toc-running-multiple-linear-regression-using-ols-in-r" class="nav-link" data-scroll-target="#running-multiple-linear-regression-using-ols-in-r">Running Multiple Linear Regression using OLS in R</a>
  <ul class="collapse">
  <li><a href="#goal-2" id="toc-goal-2" class="nav-link" data-scroll-target="#goal-2">Goal</a></li>
  <li><a href="#steps-2" id="toc-steps-2" class="nav-link" data-scroll-target="#steps-2">Steps</a></li>
  </ul></li>
  <li><a href="#output-of-multiple-linear-regression-using-ols-in-r" id="toc-output-of-multiple-linear-regression-using-ols-in-r" class="nav-link" data-scroll-target="#output-of-multiple-linear-regression-using-ols-in-r">Output of Multiple Linear Regression using OLS in R</a>
  <ul class="collapse">
  <li><a href="#beta-coefficients-estimates" id="toc-beta-coefficients-estimates" class="nav-link" data-scroll-target="#beta-coefficients-estimates">Beta Coefficients Estimates</a></li>
  <li><a href="#interpretation-of-beta-coefficient-estimates-9" id="toc-interpretation-of-beta-coefficient-estimates-9" class="nav-link" data-scroll-target="#interpretation-of-beta-coefficient-estimates-9">Interpretation of beta coefficient estimates [9]</a></li>
  <li><a href="#standard-errors" id="toc-standard-errors" class="nav-link" data-scroll-target="#standard-errors">Standard Errors</a></li>
  <li><a href="#t-values-and-p-values" id="toc-t-values-and-p-values" class="nav-link" data-scroll-target="#t-values-and-p-values">t-values and p-values</a></li>
  <li><a href="#interpretation-of-p-value-prt" id="toc-interpretation-of-p-value-prt" class="nav-link" data-scroll-target="#interpretation-of-p-value-prt">Interpretation of p-value, Pr(&gt;|t|)</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#visualizing-multiple-linear-regression-in-r" id="toc-visualizing-multiple-linear-regression-in-r" class="nav-link" data-scroll-target="#visualizing-multiple-linear-regression-in-r">Visualizing Multiple Linear Regression in R</a>
  <ul class="collapse">
  <li><a href="#goal-3" id="toc-goal-3" class="nav-link" data-scroll-target="#goal-3">Goal</a></li>
  <li><a href="#steps-3" id="toc-steps-3" class="nav-link" data-scroll-target="#steps-3">Steps</a></li>
  </ul></li>
  <li><a href="#residuals-and-residual-standard-error" id="toc-residuals-and-residual-standard-error" class="nav-link" data-scroll-target="#residuals-and-residual-standard-error">Residuals and Residual Standard Error</a>
  <ul class="collapse">
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals">Residuals</a></li>
  <li><a href="#residual-standard-error" id="toc-residual-standard-error" class="nav-link" data-scroll-target="#residual-standard-error">Residual Standard Error</a></li>
  </ul></li>
  <li><a href="#model-fit-in-multiple-linear-regression" id="toc-model-fit-in-multiple-linear-regression" class="nav-link" data-scroll-target="#model-fit-in-multiple-linear-regression">Model Fit in Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#calculating-r-squared-adjusted-r-squared-f-statistic-in-r" id="toc-calculating-r-squared-adjusted-r-squared-f-statistic-in-r" class="nav-link" data-scroll-target="#calculating-r-squared-adjusted-r-squared-f-statistic-in-r">Calculating R-squared, Adjusted R-squared, F-statistic in R</a></li>
  </ul></li>
  <li><a href="#model-prediction-in-multiple-linear-regression" id="toc-model-prediction-in-multiple-linear-regression" class="nav-link" data-scroll-target="#model-prediction-in-multiple-linear-regression">Model Prediction in Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#prediction-in-multiple-linear-regression-in-r" id="toc-prediction-in-multiple-linear-regression-in-r" class="nav-link" data-scroll-target="#prediction-in-multiple-linear-regression-in-r">Prediction in Multiple Linear Regression in R</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#assumptions-made-in-ordinary-least-squares-ols-estimation" id="toc-assumptions-made-in-ordinary-least-squares-ols-estimation" class="nav-link" data-scroll-target="#assumptions-made-in-ordinary-least-squares-ols-estimation">6 Assumptions made in Ordinary Least Squares (OLS) estimation</a>
  <ul class="collapse">
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">1. Linearity:</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence">2. Independence:</a></li>
  <li><a href="#homoscedasticity" id="toc-homoscedasticity" class="nav-link" data-scroll-target="#homoscedasticity">3. Homoscedasticity:</a></li>
  <li><a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality">4. Normality:</a></li>
  <li><a href="#no-multicollinearity" id="toc-no-multicollinearity" class="nav-link" data-scroll-target="#no-multicollinearity">5. No multicollinearity:</a></li>
  <li><a href="#no-outliers" id="toc-no-outliers" class="nav-link" data-scroll-target="#no-outliers">6. No outliers:</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="07LinearRegression.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="linear-regression." class="level1">
<h1>Linear Regression.</h1>
<p><em>July 26, 2023</em></p>
<ol type="1">
<li><p><strong>Linear regression is a statistical method for determining the relationship between one or more independent variables and a dependent variable.</strong> It is a simple and powerful data modeling and analysis tool that can assist in <strong>making predictions</strong> or <strong>identifying trends</strong>.</p></li>
<li><p>The primary goal of linear regression is to <strong>identify the best-fitting line or plane</strong> that describes the relationship between the independent and dependent variables. The regression line or plane represents the predicted value of the dependent variable given a particular value of the independent variable.</p></li>
<li><p>Linear regression, in its most basic form, involves fitting a straight line to a set of data points. When there is only one independent variable, this is known as <strong>Simple Linear Regression</strong>. When there are two or more independent variables, it is known as <strong>Multiple Linear Regression</strong>.</p></li>
<li><p>Linear regression makes several data assumptions, including that the relationship between the independent and dependent variables is linear, the errors or residuals are normally distributed, and there is no multicollinearity (high correlation) among the independent variables.</p></li>
<li><p>Linear regression can be used for a variety of purposes, including forecasting sales, predicting future trends, and estimating the impact of various variables on a specific outcome. It is widely used in a variety of fields, including economics, marketing, finance and social sciences. [1]</p></li>
</ol>
<section id="business-applications-of-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="business-applications-of-linear-regression">Business Applications of Linear Regression</h2>
<section id="marketing" class="level3">
<h3 class="anchored" data-anchor-id="marketing">Marketing</h3>
<ol type="1">
<li><p><strong>Sales forecasting</strong>: Using historical data and other factors such as <strong>pricing, advertising, and promotional activities</strong>, linear regression can be used to forecast future sales. This can assist marketers in <strong>optimizing their marketing mix</strong> and increasing sales performance.</p></li>
<li><p><strong>Customer segmentation:</strong> Linear regression can be used to <strong>analyze customer groups based on demographic, psychographic, and behavioral characteristics</strong>. Marketers can use this information to tailor their marketing messages and offerings to specific customer segments.</p></li>
<li><p><strong>Product development:</strong> Linear regression can be used to <strong>characterize the product features and attributes that are most important to customers</strong> and then optimize the product design and development process accordingly.</p></li>
<li><p><strong>Advertising effectiveness:</strong> Multiple linear regression can be used to measure the effectiveness of advertising campaigns and to identify the most effective advertising messages and media channels for reaching and persuading target customers. [2]</p></li>
</ol>
</section>
<section id="finance" class="level3">
<h3 class="anchored" data-anchor-id="finance">Finance</h3>
<ul>
<li><p><strong>Portfolio management:</strong> Linear regression can be used to examine the relationship between various variables such as interest rates, inflation, and market volatility, as well as to optimize portfolio allocation and risk management strategies.</p></li>
<li><p><strong>Credit scoring:</strong> Using Linear regression, credit scoring models can be created that predict the likelihood of default based on factors such as credit history, income, and employment status.</p></li>
<li><p><strong>Asset pricing:</strong> Linear regression can be used to <strong>estimate the fair value of assets</strong> such as stocks, bonds, and options by analyzing the relationship between various factors such as earnings, dividends, and market trends.</p></li>
<li><p><strong>Financial forecasting:</strong> Using historical data and other factors such as macroeconomic indicators and industry trends, Linear regression can be used to <strong>forecast financial outcomes such as revenue, earnings, and cash flow</strong>.</p></li>
<li><p><strong>Risk management:</strong> Linear regression can be used to <strong>analyze the relationship between different risk factors, such as interest rates, exchange rates, and commodity prices</strong>, and to develop risk management strategies that reduce exposure to these risks. [3]</p></li>
</ul>
</section>
<section id="organizational-behavior" class="level3">
<h3 class="anchored" data-anchor-id="organizational-behavior">Organizational Behavior</h3>
<p>Linear Regression can be used to investigate various aspects of organizational behavior, such as employee performance, workforce diversity, leadership effectiveness, organizational culture, and employee well-being.</p>
<ul>
<li><p><strong>Employee performance:</strong> Linear regression can be used to investigate the relationship between various factors like job satisfaction, motivation, and training and employee performance outcomes like productivity, job satisfaction, and turnover.</p></li>
<li><p><strong>Workforce diversity:</strong> Linear regression can be used to examine the relationship between demographic diversity, cultural diversity, and social diversity and organizational outcomes such as creativity, innovation, and problem-solving.</p></li>
<li><p><strong>Leadership effectiveness</strong>: Linear regression can be used to examine the relationship between various factors like leadership style, communication, and decision-making and leadership outcomes like employee motivation and job satisfaction.</p></li>
<li><p><strong>Organizational culture:</strong> Linear regression can be used to investigate the relationship between organizational values, norms, and beliefs and organizational outcomes such as employee engagement, retention, and performance.</p></li>
<li><p><strong>Employee well-being:</strong> Multiple linear regression can be used to examine the relationship between work-life balance, social support, and job demands and employee well-being outcomes such as stress, burnout, and health. [4]</p></li>
</ul>
</section>
</section>
</section>
<section id="simple-linear-regression" class="level1">
<h1>Simple Linear Regression</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<ol type="1">
<li><p>Simple linear regression is used to model the relationship between a dependent variable and <strong>a single independent variable</strong>.</p></li>
<li><p>The goal of simple linear regression is to find the <strong>best fit</strong> line<strong>.</strong></p></li>
<li><p>The best fit line is determined by <strong>minimizing the sum of the squared distances between the actual and predicted values</strong> of the dependent variable based on the independent variable.</p></li>
<li><p>The independent variable is plotted on the x-axis, and the dependent variable is plotted on the y-axis, to create a scatter plot and visualize the best fit line. [5]</p></li>
</ol>
</section>
<section id="model-of-simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-of-simple-linear-regression">Model of Simple Linear Regression</h2>
<ol type="1">
<li>The model equation for a simple linear regression model is:</li>
</ol>
<span class="math display">\[\begin{equation}
\label{eq:slr}
y = β_0 + β_1x + ε
\end{equation}\]</span>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable</li>
<li><span class="math inline">\(x\)</span> is the independent variable</li>
<li><span class="math inline">\(β_0\)</span> is the intercept (the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>)</li>
<li><span class="math inline">\(β_1\)</span> is the slope (the change in y for a one-unit change in x)</li>
<li><span class="math inline">\(ε\)</span> is the error term (represents the random variability in the data)</li>
</ul>
<ol start="2" type="1">
<li><p>The goal of the simple linear regression model shown in (<span class="math inline">\(\ref{eq:slr}\)</span>), is to estimate the values of <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span> given that <strong>minimize the sum of squared errors (SSE)</strong> between the observed values of <span class="math inline">\(y\)</span> and the predicted values of <span class="math inline">\(y\)</span>.</p></li>
<li><p>There are several methods for estimating the values of <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span>, the most common of which is the called <strong>Ordinary Least Squares (OLS)</strong>.</p></li>
<li><p>The <strong>Ordinary Least Squares (OLS)</strong> method calculates the values of</p>
<p><span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span> that minimize the sum of squared errors (SSE) between the observed and predicted values of <span class="math inline">\(y\)</span>.</p></li>
<li><p>After estimating the values of <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span>, the model can be used to <strong>predict the value of</strong> <span class="math inline">\(y\)</span>, for any given value of <span class="math inline">\(x\)</span>. [6]</p></li>
</ol>
</section>
<section id="running-simple-linear-regression-in-r" class="level2">
<h2 class="anchored" data-anchor-id="running-simple-linear-regression-in-r">Running Simple Linear Regression in R</h2>
<section id="goal" class="level3">
<h3 class="anchored" data-anchor-id="goal">Goal</h3>
<ul>
<li><p>Consider the mtcars data. Suppose we need to fit a simple linear regression model to predict <code>mpg</code> (miles per gallon) based on the predictor variable: <code>wt</code> (weight).</p></li>
<li><p>We would like to estimate it using Ordinary Least Squares.</p></li>
</ul>
</section>
<section id="steps" class="level3">
<h3 class="anchored" data-anchor-id="steps">Steps</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load mtcars dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a simple linear regression model</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>model0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data =</span> mtcars)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print the model summary</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5432 -2.3647 -0.1252  1.4096  6.8727 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
wt           -5.3445     0.5591  -9.559 1.29e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.046 on 30 degrees of freedom
Multiple R-squared:  0.7528,    Adjusted R-squared:  0.7446 
F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
</div>
</div>
<ol type="1">
<li><p>Using the <code>lm()</code> function in R, we can fit a simple linear regression model in which <strong>the dependent variable <code>(mpg)</code> is regressed on the independent variable <code>(wt)</code></strong>.</p></li>
<li><p>The data argument specifies the dataset, and <code>mpg ~ wt</code> specifies the linear regression model formula, where <code>mpg</code> is the dependent variable and <code>wt</code> is the independent variable.</p></li>
<li><p>The <code>summary()</code> function is called to print the model’s results. The output gives the estimated coefficients, standard errors, t-statistics, and p-values for each variable in the model, as well as the overall R-squared value and other statistics related to model fit.</p></li>
<li><p>Substituting the values of <span class="math inline">\(\beta\)</span> coefficients from the above regression output, we can write the model as follows.</p></li>
</ol>
<span class="math display">\[\begin{equation}
\label{eq:slr2}
mpg = 37.2851 -5.3445 wt + ε
\end{equation}\]</span>
</section>
</section>
<section id="visualizing-simple-linear-regression-in-r" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-simple-linear-regression-in-r">Visualizing Simple Linear Regression in R</h2>
<section id="goal-1" class="level3">
<h3 class="anchored" data-anchor-id="goal-1">Goal</h3>
<ul>
<li><p>Suppose we need to visualize the above simple linear regression model to predict <code>mpg</code> (miles per gallon) based on the predictor variable: <code>wt</code> (weight).</p></li>
<li><p>One way of doing this is to create a <strong>scatter plot</strong>.</p></li>
</ul>
</section>
<section id="steps-1" class="level3">
<h3 class="anchored" data-anchor-id="steps-1">Steps</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the data and the regression line</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars<span class="sc">$</span>wt, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     mtcars<span class="sc">$</span>mpg, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Simple Linear Regression"</span>, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Weight (in 1000 lbs)"</span>, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Miles per Gallon"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model0, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07LinearRegression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<ol type="1">
<li><p>We create a scatter plot of the data using the <code>plot()</code> function, where the x-axis represents the weight of the car in thousands of lbs, and the y-axis represents the miles per gallon.</p></li>
<li><p>We also use the <code>main</code> and <code>xlab</code>, <code>ylab</code> arguments to add a title and axes labels.</p></li>
<li><p>Finally, we use the <code>abline()</code> function to add the regression line to the plot, which takes the model object as an argument and plots the regression line. Using the <code>col</code> argument, we change the color of the line.</p></li>
<li><p>This code generates a scatter plot of the data with the regression line overlaid on top, allowing us to easily visualize the relationship between the dependent and independent variables. [7]</p></li>
</ol>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<section id="overview-1" class="level2">
<h2 class="anchored" data-anchor-id="overview-1">Overview</h2>
<ol type="1">
<li><p>Multiple linear regression is a statistical technique used to model the relationship between <strong>a dependent variable and multiple independent variables</strong>.</p></li>
<li><p>The goal of multiple linear regression is to <strong>find the linear equation that best explains the relationship</strong> between the dependent variable and the independent variables. [8]</p></li>
</ol>
</section>
<section id="model-of-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-of-multiple-linear-regression">Model of Multiple Linear Regression</h2>
<ol type="1">
<li>The model equation for a multiple linear regression model with p independent variables is:</li>
</ol>
<span class="math display">\[\begin{equation}
\label{eq:mlr}
y = β_0 + β_1x_1 + β_2x_2 + … + β_px_p + ε
\end{equation}\]</span>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable</li>
<li><span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_p\)</span> are the independent variables</li>
<li><span class="math inline">\(β_0\)</span> is the intercept (the value of <span class="math inline">\(y\)</span> when all independent variables are 0)</li>
<li><span class="math inline">\(β_1\)</span>, <span class="math inline">\(β_2\)</span>, …, <span class="math inline">\(β_p\)</span> are the coefficients that represent the change in <span class="math inline">\(y\)</span> for a one-unit change in each independent variable, holding all other variables constant</li>
<li><span class="math inline">\(ε\)</span> is the error term (represents the random variability in the data)</li>
</ul>
<p>The model given in (<span class="math inline">\(\ref{eq:mlr}\)</span>) is the most popular regression model.</p>
</section>
<section id="ordinary-least-squares-ols-estimation" class="level2">
<h2 class="anchored" data-anchor-id="ordinary-least-squares-ols-estimation">Ordinary Least Squares (OLS) Estimation</h2>
<ol type="1">
<li><p>Ordinary Least Squares (OLS) regression is the most widely used statistical estimation method for multiple linear regression.</p></li>
<li><p>OLS estimates the values of <span class="math inline">\(β_0\)</span>, <span class="math inline">\(β_1\)</span>, <span class="math inline">\(β_2\)</span>, …, <span class="math inline">\(β_p\)</span> that <strong>minimize the sum of squared errors (SSE) between the observed values of</strong> <span class="math inline">\(y\)</span> <strong>and the predicted values of</strong> <span class="math inline">\(y\)</span><strong>.</strong></p></li>
<li><p>Once the values of <span class="math inline">\(β_0\)</span>, <span class="math inline">\(β_1\)</span>, <span class="math inline">\(β_2\)</span>, …, <span class="math inline">\(β_p\)</span> have been estimated, the model can be used to <strong>predict the value of</strong> <span class="math inline">\(y\)</span> for any given values of <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_p\)</span>. [8]</p></li>
</ol>
</section>
<section id="running-multiple-linear-regression-using-ols-in-r" class="level2">
<h2 class="anchored" data-anchor-id="running-multiple-linear-regression-using-ols-in-r">Running Multiple Linear Regression using OLS in R</h2>
<section id="goal-2" class="level3">
<h3 class="anchored" data-anchor-id="goal-2">Goal</h3>
<ul>
<li><p>Consider the mtcars data. Suppose we need to fit a multiple linear regression model to predict <code>mpg</code> (miles per gallon) based on the predictor variables: <code>disp</code> (displacement), <code>hp</code> (horsepower), and <code>wt</code> (weight) and <code>cyl</code> (number of cylinders).</p></li>
<li><p>We would like to estimate it using Ordinary Least Squares.</p></li>
</ul>
</section>
<section id="steps-2" class="level3">
<h3 class="anchored" data-anchor-id="steps-2">Steps</h3>
<ol type="1">
<li>At the outset, we need to ensure that the data types are correct</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># `cyl` (number of cylinders) needs to set as a factor</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>cyl <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mtcars<span class="sc">$</span>cyl)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># verify that `cyl` is a factor</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars<span class="sc">$</span>cyl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 3 levels "4","6","8": 2 2 1 2 3 2 3 1 1 2 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># verify that `mpg`, `disp`, `hp`, `wt` are numeric</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars<span class="sc">$</span>mpg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:32] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars<span class="sc">$</span>disp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:32] 160 160 108 258 360 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:32] 110 110 93 110 175 105 245 62 95 123 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:32] 2.62 2.88 2.32 3.21 3.44 ...</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Now, we can run the multiple linear regression.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a multiple linear regression model</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> hp <span class="sc">+</span> wt <span class="sc">+</span> cyl, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> mtcars)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the summary of the model</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + hp + wt + cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2740 -1.0349 -0.3831  0.9810  5.4192 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 36.002405   2.130726  16.897 1.54e-15 ***
disp         0.004199   0.012917   0.325  0.74774    
hp          -0.023517   0.012216  -1.925  0.06523 .  
wt          -3.428626   1.055455  -3.248  0.00319 ** 
cyl6        -3.466011   1.462979  -2.369  0.02554 *  
cyl8        -3.753227   2.813996  -1.334  0.19385    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.482 on 26 degrees of freedom
Multiple R-squared:  0.8578,    Adjusted R-squared:  0.8305 
F-statistic: 31.37 on 5 and 26 DF,  p-value: 3.18e-10</code></pre>
</div>
</div>
<ul>
<li><p>The <code>lm()</code> function is used to fit the model, and the data argument specifies the <code>mtcars</code> dataset.</p></li>
<li><p>The model formula specifies that <code>mpg</code> is the response variable and <code>cyl</code>, <code>disp</code>, <code>hp</code>, and <code>wt</code> are the predictor variables. The data argument specifies the dataset that the variables are taken from, which in this case is the mtcars dataset.</p></li>
<li><p>Recall that <code>cyl</code> is a categorical, factor variable that takes three levels <span class="math inline">\(cyl = {4, 6, 8}\)</span> corresponding to four, six and eight cylinder cars.</p></li>
<li><p>R sets the level <span class="math inline">\(cyl = 4\)</span> to be the base level by default. It creates two dummy variables <code>cyl6</code> and <code>cyl8</code> corresponding to six and eight cylinder cars. We have, <code>cyl6=1</code> for six cylinder cars, <code>cyl6=0</code> otherwise. We have, <code>cyl8=1</code> for eight cylinder cars, <code>cyl8=0</code> otherwise.</p></li>
<li><p>The beta coefficient estimate for <code>cyl6</code> represents the expected difference in <code>mpg</code> between cars with six cylinders and cars with four cylinders.</p></li>
<li><p>The equation for the multiple linear regression model to predict <code>mpg</code> (miles per gallon) based on the predictor variables: <code>disp</code> (displacement), <code>hp</code> (horsepower), and <code>wt</code> (weight) and <code>cyl</code> (number of cylinders) is given as follows:</p></li>
</ul>
<span class="math display">\[\begin{equation}
\label{eq:mlr2}
mpg = 36.0024 + 0.0042disp - 0.0235hp - 3.4286 wt - 3.4660 cyl_6 - 3.7532 cyl_8 + ε
\end{equation}\]</span>
<ol start="4" type="1">
<li>The <code>summary()</code> function is used to view a summary of the model, which includes information such as the coefficients for each predictor variable, the standard errors, t-values, and p-values for each coefficient, the R-squared value, and more. This summary output can be used to interpret the results of the multiple linear regression model. [9]</li>
</ol>
</section>
</section>
<section id="output-of-multiple-linear-regression-using-ols-in-r" class="level2">
<h2 class="anchored" data-anchor-id="output-of-multiple-linear-regression-using-ols-in-r">Output of Multiple Linear Regression using OLS in R</h2>
<section id="beta-coefficients-estimates" class="level3">
<h3 class="anchored" data-anchor-id="beta-coefficients-estimates">Beta Coefficients Estimates</h3>
<ol type="1">
<li><p>The beta coefficient estimate for a predictor variable represents the <strong>change in the response variable that is associated with a one-unit increase in that predictor variable</strong>, while holding all other predictor variables constant. In other words, it represents the effect that each predictor variable has on the response variable, after <strong>controlling for the effects of all other predictor variables</strong> in the model.</p></li>
<li><p>In the output of the multiple linear regression model, the “Coefficients” table shows the estimates of the beta coefficients (also known as regression coefficients or slope coefficients) for each predictor variable in the model. [9]</p></li>
<li><p>We can use the following code to extract the beta coefficients.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">=</span> model<span class="sc">$</span>coefficients</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(betas,<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        disp          hp          wt        cyl6        cyl8 
    36.0024      0.0042     -0.0235     -3.4286     -3.4660     -3.7532 </code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We can also visualize the beta coefficients. We use coefplot() in the arm package to plot the coefficients and their 95% credible intervals.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the arm package</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
arm (Version 1.13-1, built: 2022-8-25)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Working directory is /cloud/project</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use coefplot() to plot the coefficients of the model</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefplot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07LinearRegression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="768"></p>
</div>
</div>
</section>
<section id="interpretation-of-beta-coefficient-estimates-9" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-beta-coefficient-estimates-9">Interpretation of beta coefficient estimates [9]</h3>
<p><strong>Example 1:</strong></p>
<ul>
<li><p>The <strong>beta coefficient estimate for <code>disp</code> represents the estimated change in the “mpg” response variable associated with a one-unit increase in the <code>disp</code> predictor variable</strong>, while holding all other predictors constant.</p></li>
<li><p>The beta coefficient estimate for <code>disp</code> is 0.004199. This means that, on average, <strong>as the <code>disp</code> variable (engine displacement, in cubic inches) increases by one unit, the predicted <code>mpg</code> value for the car increases by 0.004199 units</strong>, while holding all other predictor variables constant.</p></li>
<li><p>However, as the p-value for <code>disp</code> is greater than the chosen threshold of 0.05, there is <strong>no evidence to suggest that this change is statistically significant at the 5% level,</strong> after controlling for the effects of the other predictor variables in the model. Therefore, it may not be appropriate to make any conclusive statements about the relationship between <code>disp</code> and <code>mpg</code> based solely on the beta coefficient estimate for <code>disp</code> in this model.</p></li>
</ul>
<p><strong>Example 2:</strong></p>
<ul>
<li><p>The <strong>the beta coefficient estimate for <code>wt</code> represents the estimated change in the <code>mpg</code> response variable associated with a one-unit increase in the <code>wt</code> predictor variable</strong>, while holding all other predictors constant.</p></li>
<li><p>The beta coefficient estimate for <code>wt</code> is -3.428626. This means that, on average, <strong>as the <code>wt</code> variable (weight of the car in thousands of pounds) increases by one unit, the predicted <code>mpg</code> value for the car decreases by 3.428626 units</strong>, while holding all other predictor variables constant.</p></li>
</ul>
<p><strong>Example 3:</strong></p>
<ul>
<li><p>The beta coefficient estimate for <code>cyl6</code> is -3.466011. This means that, on average, cars with six cylinders have a predicted “mpg” value that is 3.466011 lower than cars with four cylinders, after accounting for the effects of the other predictor variables in the model.</p></li>
<li><p>Similarly, the beta coefficient estimate for <code>cyl8</code> is -3.753227. This means that, on average, cars with eight cylinders have a predicted <code>mpg</code> value that is 3.753227 lower than cars with four cylinders, after accounting for the effects of the other predictor variables in the model.</p></li>
</ul>
</section>
<section id="standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="standard-errors">Standard Errors</h3>
<ol type="1">
<li><p>In multiple linear regression, the standard error is <strong>a measure of the variability of the estimated coefficients of the predictor variables</strong> in the model.</p></li>
<li><p>It reflects the variability of the estimated coefficients due to the random error in the data. <strong>It represents the average amount that the estimated coefficients would vary if we fit the same model to different samples of data from the population.</strong></p></li>
<li><p>The standard error is estimated from the residual standard error of the model, which is a measure of the variability of the residuals or the differences between the predicted and observed values of the response variable.</p></li>
<li><p><strong>A smaller standard error means a more precise estimate of the coefficient</strong>, and more likely to accurately reflect the true relationship between the independent variable and the dependent variable. [9]</p></li>
</ol>
<p><strong>Example 1:</strong></p>
<ol type="1">
<li><p>In the output of the linear regression model, “Std. Error” of wt refers to the standard error of the estimate for the coefficient of the independent variable wt (weight of the car).</p></li>
<li><p>The “Std. Error” of <code>wt</code> is given as 1.0554. This means that the estimated coefficient for <code>wt</code> is expected to vary by about 1.0554 units across different samples of data that could have been collected. [9]</p></li>
</ol>
</section>
<section id="t-values-and-p-values" class="level3">
<h3 class="anchored" data-anchor-id="t-values-and-p-values">t-values and p-values</h3>
<ol type="1">
<li><p><strong>The t-value measures the number of standard errors the estimated coefficient is away from zero.</strong> <strong>It is calculated by dividing the estimated coefficient by its standard error.</strong></p></li>
<li><p><strong>A higher absolute t-value suggests that the estimated coefficient is more significant</strong> and more likely to accurately reflect the true relationship between the independent variable and the dependent variable.</p></li>
<li><p>It’s important to note that the t-value is used to calculate the p-value for the coefficient estimate. A small p-value indicates that the coefficient is statistically significant and not likely to have occurred by chance.</p></li>
<li><p><strong>The p-value is the probability of observing a t-value as extreme or more extreme than the observed t-value, assuming that the true coefficient is zero.</strong></p></li>
<li><p>A small p-value indicates that it is unlikely that the observed t-value occurred by chance, and suggests that the true coefficient is not zero (i.e., there is a statistically significant relationship between wt and mpg). [9]</p></li>
</ol>
<p><strong>Example 1:</strong></p>
<ol type="1">
<li><p>In the output, the “t-value” of wt is given as -3.248. This means that the estimated coefficient for <code>wt</code> is -3.248 standard errors away from zero.</p></li>
<li><p><strong>A negative t-value indicates that there is an inverse relationship between the independent variable and the dependent variable. Since the t-value is relatively large (in absolute value) and negative, it suggests that the estimated coefficient for <code>wt</code> is statistically significant and has a significant impact on the dependent variable <code>(mpg)</code>.</strong></p></li>
<li><p>In this case, the p-value for <code>wt</code> is 0.00319, indicating that the estimated coefficient for <code>wt</code> is statistically significant and has a significant impact on the dependent variable.</p></li>
<li><p>In the output, the “t-value” of <code>wt</code> is -3.248, and the degrees of freedom for the t-distribution is 26 (which is the sample size minus the number of parameters estimated in the model).</p></li>
</ol>
<p>[9]</p>
</section>
<section id="interpretation-of-p-value-prt" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-p-value-prt">Interpretation of p-value, Pr(&gt;|t|)</h3>
<p><strong>Example 2:</strong></p>
<ol type="1">
<li><p>In the output, the beta coefficient estimate for <code>disp</code> is 0.004199 with a standard error of 0.012917, a t-value of 0.325, and a p-value of 0.74774.</p></li>
<li><p>The p-value for <code>disp</code> is greater than the chosen threshold of 0.05, indicating that the beta coefficient estimate for “disp” is not statistically significant at the 5% level. This means that, after controlling for the effects of the other predictor variables in the model, there is no evidence to suggest that the <code>disp</code> variable has a significant linear relationship with the <code>mpg</code> response variable.</p></li>
<li><p>Therefore, the <code>disp</code> variable is not a significant predictor of the <code>mpg</code> response variable in the model. [9]</p></li>
</ol>
<p><strong>Example 3:</strong></p>
<ol type="1">
<li><p>In the output, the beta coefficient estimate for <code>wt</code> is -3.428626 with a standard error of 1.055455, a t-value of -4.223, and a p-value of 0.0002.</p></li>
<li><p>The p-value for <code>wt</code> is less than the chosen threshold of 0.05, indicating that the beta coefficient estimate for <code>wt</code> is statistically significant at the 5% level.</p></li>
<li><p>This means that, after controlling for the effects of the other predictor variables in the model, there is evidence to suggest that the <code>wt</code> variable has a significant linear relationship with the <code>mpg</code> response variable. [9]</p></li>
</ol>
<p><strong>Example 4:</strong></p>
<ol type="1">
<li><p>In the output, the beta coefficient estimate for <code>cyl_6</code> is -3.466011 with a standard error of 1.462979, a t-value of -2.369, and a p-value of 0.02554. Similarly, the beta coefficient estimate for <code>cyl_8</code> is -3.753227 with a standard error of 2.813996, a t-value of -1.334, and a p-value of 0.19385.</p></li>
<li><p>The p-value for <code>cyl_6</code> is greater than the chosen threshold of 0.05, indicating that the beta coefficient estimate for <code>cyl_6</code> is not statistically significant at the 5% level.</p></li>
<li><p>This means that, after controlling for the effects of the other predictor variables in the model, there is no evidence to suggest that the average <code>mpg</code> for cars with six cylinders is significantly different from that for cars with four cylinders.</p></li>
<li><p>On the other hand, the p-value for <code>cyl_8</code> is less than 0.05, indicating that the beta coefficient estimate for <code>cyl_8</code> is statistically significant at the 5% level.</p></li>
<li><p>This means that, after controlling for the effects of the other predictor variables in the model, there is evidence to suggest that the average <code>mpg</code> for cars with eight cylinders is significantly different from that for cars with four cylinders.</p></li>
<li><p>Also, the negative beta coefficient estimate for <code>cyl_8</code> indicates that, on average, cars with eight cylinders have a lower predicted <code>mpg</code> value than cars with four cylinders, while holding all other predictor variables constant. [9]</p></li>
</ol>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h3>
<ol type="1">
<li><p>In multiple linear regression, the confidence interval can be interpreted as <strong>a range of values that we are x% confident contains the true population coefficient</strong>, where x is the chosen level of confidence.</p></li>
<li><p><strong>The most common level of confidence is 95%</strong>, but other levels of confidence, such as 90% or 99%, can also be used.</p></li>
<li><p>The confidence interval is based on the <strong>standard error</strong> and the t-distribution, which takes into account the <strong>sample size</strong> and the <strong>degrees of freedom</strong> of the model.</p></li>
<li><p>In the output of the linear regression model, we can calculate the confidence interval for the beta coefficient of wt (weight of the car) at a desired confidence level (e.g., 95%) using the t-distribution.</p></li>
<li><p>The following code will output the confidence intervals</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the 95% confidence intervals of the estimated coefficients</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %       97.5 %
(Intercept) 31.62263411 40.382174889
disp        -0.02235276  0.030750496
hp          -0.04862749  0.001594483
wt          -5.59814537 -1.259106203
cyl6        -6.47320809 -0.458813851
cyl8        -9.53747788  2.031023933</code></pre>
</div>
</div>
<ol start="6" type="1">
<li><p>In the output, the confidence intervals of the estimated coefficients are displayed in a table with two columns, “2.5 %” and “97.5 %”.</p></li>
<li><p>For example, the confidence interval for the estimated coefficient of <code>wt</code> is (-5.985, -1.617), which means that we are 95% confident that the true population coefficient for <code>wt</code> lies within this range.</p></li>
<li><p><strong>If the confidence interval for a coefficient does not include 0, we can conclude that the corresponding predictor variable is likely to be a significant predictor of the response variable at the 5% level of significance.</strong></p></li>
<li><p>The formula for the confidence interval in multiple linear regression is: <span class="math inline">\(CI = \beta ± t * SE\)</span>, where $t” represents the t-value and <span class="math inline">\(SE\)</span> represents the Standard Error.</p></li>
</ol>
<ul>
<li>the coefficient estimate is the point estimate of the coefficient,</li>
<li>the t-value is the critical value from the t-distribution with <span class="math inline">\(n-p-1\)</span> degrees of freedom, where</li>
<li><span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(p\)</span> is the number of predictor variables in the model,</li>
<li>the standard error <span class="math inline">\(SE\)</span> is a measure of the variability of the estimated coefficient</li>
<li>The critical value from the t-distribution depends on the level of confidence and the degrees of freedom. For example, for a 95% confidence interval with 25 observations and 3 predictor variables, the critical value is approximately 2.306. [10]</li>
</ul>
</section>
</section>
<section id="visualizing-multiple-linear-regression-in-r" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-multiple-linear-regression-in-r">Visualizing Multiple Linear Regression in R</h2>
<section id="goal-3" class="level3">
<h3 class="anchored" data-anchor-id="goal-3">Goal</h3>
<ul>
<li><p>Suppose we need to visualize the above multiple linear regression model to predict <code>mpg</code> (miles per gallon) based on multiple predictor variables.</p></li>
<li><p>There is no good way of doing this. One limited way of doing this is to create a <strong>scatter plot matrix</strong>.</p></li>
</ul>
</section>
<section id="steps-3" class="level3">
<h3 class="anchored" data-anchor-id="steps-3">Steps</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot matrix of the variables</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:arm':

    logit</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatterplotMatrix</span>(<span class="sc">~</span>mpg <span class="sc">+</span> wt <span class="sc">+</span> hp <span class="sc">+</span> disp, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> mtcars)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the regression line to the scatterplot matrix</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abline(model, col = "blue"): only using the first two of 6
regression coefficients</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07LinearRegression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<ol type="1">
<li><p>This code will create a scatterplot matrix of the variables (<code>mpg</code>, <code>wt</code>, <code>hp</code>, <code>disp</code>) in the mtcars data set, and will add a regression line to the plot to visualize the relationship between <code>mpg</code>, <code>wt</code>, <code>hp</code>,`disp.</p></li>
<li><p>The scatterplot matrix will show the scatterplots of all three variables, and the regression line will show the predicted relationship between <code>mpg</code>, <code>wt</code>, <code>hp</code>, <code>disp</code>.</p></li>
<li><p>Note that we will need to have the car package installed in order to create the scatterplot matrix. If we don’t have the package installed, we can install it by running <code>install.packages("car")</code>.</p></li>
</ol>
</section>
</section>
<section id="residuals-and-residual-standard-error" class="level2">
<h2 class="anchored" data-anchor-id="residuals-and-residual-standard-error">Residuals and Residual Standard Error</h2>
<section id="residuals" class="level3">
<h3 class="anchored" data-anchor-id="residuals">Residuals</h3>
<ol type="1">
<li><p>In the output of the linear regression model, “Residuals” refer to the <strong>differences between the predicted values of the dependent variable (<code>mpg</code>) and the actual observed values of the dependent variable in the dataset <code>(mtcars)</code>.</strong></p></li>
<li><p>The residuals are important to examine because they can provide information about the accuracy of the model. <strong>Ideally, the residuals should be normally distributed around zero</strong>, indicating that the model is accurately predicting the values of the dependent variable. If the residuals are not normally distributed or have a pattern, this could indicate that the model is not accurately predicting the values of the dependent variable and may require further refinement.</p></li>
<li><p>In the above example, the residuals are the differences between the predicted values and actual values of the dependent variable cyl, <strong>which cannot be explained by the independent variables</strong> (<code>cyl</code>, <code>disp</code>, <code>hp</code>, and <code>wt</code>) included in the model.</p></li>
<li><p>Analyzing the residuals can help us check whether the assumptions of the multiple linear regression model are met, and can also help us <strong>identify outliers or influential observations</strong> that may be affecting the model fit.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review the Residuals</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + hp + wt + cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2740 -1.0349 -0.3831  0.9810  5.4192 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 36.002405   2.130726  16.897 1.54e-15 ***
disp         0.004199   0.012917   0.325  0.74774    
hp          -0.023517   0.012216  -1.925  0.06523 .  
wt          -3.428626   1.055455  -3.248  0.00319 ** 
cyl6        -3.466011   1.462979  -2.369  0.02554 *  
cyl8        -3.753227   2.813996  -1.334  0.19385    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.482 on 26 degrees of freedom
Multiple R-squared:  0.8578,    Adjusted R-squared:  0.8305 
F-statistic: 31.37 on 5 and 26 DF,  p-value: 3.18e-10</code></pre>
</div>
</div>
<ol start="5" type="1">
<li><p>In the output, the “Residuals” section includes information about the minimum and maximum residuals, as well as the first and third quartiles, the median of the residuals. This information can be used to assess the distribution and potential patterns in the residuals.</p></li>
<li><p>To extract the residuals from a multiple linear regression model in R, we can use the <strong><code>resid()</code></strong> function on the model object.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the residuals</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">resid</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="7" type="1">
<li>We can also create a <strong>scatter plot of the residuals against the fitted values (predicted values)</strong> to visually inspect whether the assumptions of the model are met:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the residuals against the fitted values</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model), residuals,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Fitted Values"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residual Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07LinearRegression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<ol start="8" type="1">
<li><p>This will create a <strong>scatter plot of the residuals against the fitted values</strong> In this plot, we want to see a random scatter of points around the horizontal zero line, indicating that the residuals have a mean of zero and are evenly distributed across the range of fitted values.</p></li>
<li><p>If we see any patterns or trends in the residuals, such as a curved shape or a U-shape, this may indicate that the assumptions of the multiple linear regression model are not met and that the model may need to be modified or improved.</p></li>
<li><p>We can also calculate <strong>summary statistics for the residuals</strong>, such as the mean, standard deviation, and range, using the summary() function on the residuals object.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-4.2740 -1.0349 -0.3831  0.0000  0.9810  5.4192 </code></pre>
</div>
</div>
<pre><code>\[11\]</code></pre>
</section>
<section id="residual-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="residual-standard-error">Residual Standard Error</h3>
<ol type="1">
<li><p>In the output of the linear regression model, “Residual standard error” refers to the <strong>standard deviation of the residuals</strong>.</p></li>
<li><p>It indicates how much the predicted values of the dependent variable deviate from the actual observed values, on average.</p></li>
<li><p>A lower residual standard error indicates that the model is better at predicting the values of the dependent variable.</p></li>
<li><p>The residual standard error provides a measure of the amount of variation in the dependent variable (<code>mpg</code>) that is not explained by the independent variables (<code>cyl</code>, <code>disp</code>, <code>hp</code>, and <code>wt</code>) included in the model.</p></li>
<li><p>In R, we can extract the RSE from a multiple linear regression model using the <code>summary()</code> function on the model object.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the RSE</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>rse <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>sigma</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>rse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.481678</code></pre>
</div>
</div>
<ol start="5" type="1">
<li><p>In the output, the “Residual standard error” value is given as 2.639. This means that, on average, the predicted values of mpg deviate from the actual observed values by about 2.639 units.</p></li>
<li><p>It’s important to note that the residual standard error should be <strong>considered in the context of the range of values of the dependent variable</strong>. In this case, since the range of mpg values in the mtcars dataset is 10.4 to 33.9, a residual standard error of 2.639 might be considered reasonable, indicating that the model is making relatively accurate predictions of the dependent variable. [11]</p></li>
</ol>
</section>
</section>
<section id="model-fit-in-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-fit-in-multiple-linear-regression">Model Fit in Multiple Linear Regression</h2>
<ol type="1">
<li><p>The model fit in multiple linear regression refers to how well the regression model fits the observed data. There are several measures of model fit that can be used to evaluate the performance of a multiple linear regression model.</p></li>
<li><p><strong>R-squared:</strong> One commonly used measure of model fit is the R-squared value, which represents the proportion of the total variability in the response variable that is explained by the predictor variables in the model.</p></li>
</ol>
<ul>
<li><p>R-squared is a statistical measure that represents the proportion of variance in the dependent variable that can be explained by the independent variables in the model.</p></li>
<li><p>R-squared is sometimes called the coefficient of determination or the goodness-of-fit measure.</p></li>
<li><p>R-squared <strong>ranges from 0 to 1</strong>, with higher values indicating that the model explains a greater proportion of the variance in the dependent variable.</p></li>
<li><p>An R-squared of 0 indicates that the model does not explain any of the variance in the dependent variable, while an R-squared of 1 indicates that the model perfectly explains all of the variance in the dependent variable.</p></li>
<li><p>However, it is important to note that <strong>a high R-squared does not necessarily mean that the model is a good fit for the data</strong> or that it will be a good predictor. For example, an overfitted model that includes too many predictor variables may have a high R-squared, but it may not generalize well to new data.</p></li>
<li><p>Additionally, an R-squared of 0 does not necessarily mean that the model is not useful, as it may still provide some insight into the relationships between the variables in the model.</p></li>
</ul>
<ol start="3" type="1">
<li><strong>Adjusted R-squared:</strong></li>
</ol>
<ul>
<li><p>The adjusted R-squared is a statistical measure of fit that <strong>accounts for the number of predictor variables included in the model</strong>.</p></li>
<li><p>Recall that the R-squared indicates the proportion of variation in the dependent variable (the variable we are trying to predict) that can be explained by the independent variables (the predictors) in the model.</p></li>
<li><p>However, as we add more variables to the model, the R-squared value will typically increase, even if the added variables do not actually improve the model’s ability to predict the dependent variable.</p></li>
<li><p>To address this issue, the <strong>“Adjusted R-squared” statistic adjusts for the number of predictor variables in the model</strong>. It penalizes models that include more variables that do not improve the model’s ability to predict the dependent variable.</p></li>
<li><p>The adjusted R-squared is calculated using the following formula: <span class="math inline">\(AdjRSquared = 1 - [(1 - RSquared) * (n - 1) / (n - k - 1)]\)</span>, where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(k\)</span> is the number of predictor variables in the model.</p></li>
<li><p>The Adjusted R-squared will always be lower than the R-squared, since it adjusts for the number of predictor variables.</p></li>
<li><p><strong>A higher Adjusted R-squared value indicates that the model is a better fit for the data</strong>, as it indicates that more of the variation in the dependent variable is being explained by the independent variables, and not just due to chance or noise.</p></li>
</ul>
<ol start="4" type="1">
<li><strong>F-statistic:</strong></li>
</ol>
<ul>
<li><p>In linear regression, the F-statistic is a statistical measure that is used to <strong>test the overall significance of the model</strong>.</p></li>
<li><p>It measures the <strong>ratio of the explained variance to the unexplained variance in the dependent variable</strong>.</p></li>
<li><p>It is calculated by dividing the mean square for the model by the mean square for the residuals.</p></li>
<li><p>The F-statistic is based on the <strong>null hypothesis that all of the coefficients in the model are equal to zero</strong>, indicating that the independent variables do not have any effect on the dependent variable.</p></li>
<li><p>The <strong>alternative hypothesis is that at least one of the coefficients in the model is not equal to zero</strong>, indicating that the independent variables do have an effect on the dependent variable.</p></li>
<li><p><strong>If the F-statistic is large and the associated p-value is small,</strong> this provides evidence against the null hypothesis and suggests that the model is a good fit for the data.</p></li>
<li><p>However, if the F-statistic is small and the associated p-value is large, this suggests that the model is not a good fit for the data, and that the null hypothesis cannot be rejected.</p></li>
<li><p>It is important to note that while the F-statistic tests the overall significance of the model, <strong>it does not provide information about the individual significance of the coefficients or the relative importance of the predictor variables.</strong></p></li>
</ul>
<section id="calculating-r-squared-adjusted-r-squared-f-statistic-in-r" class="level3">
<h3 class="anchored" data-anchor-id="calculating-r-squared-adjusted-r-squared-f-statistic-in-r">Calculating R-squared, Adjusted R-squared, F-statistic in R</h3>
<ol type="1">
<li>We can read the R-squared, Adjusted R-squared, F-statistic from the output of the <code>summary()</code> function.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the model summary</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + hp + wt + cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2740 -1.0349 -0.3831  0.9810  5.4192 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 36.002405   2.130726  16.897 1.54e-15 ***
disp         0.004199   0.012917   0.325  0.74774    
hp          -0.023517   0.012216  -1.925  0.06523 .  
wt          -3.428626   1.055455  -3.248  0.00319 ** 
cyl6        -3.466011   1.462979  -2.369  0.02554 *  
cyl8        -3.753227   2.813996  -1.334  0.19385    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.482 on 26 degrees of freedom
Multiple R-squared:  0.8578,    Adjusted R-squared:  0.8305 
F-statistic: 31.37 on 5 and 26 DF,  p-value: 3.18e-10</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Alternately, we can also extract the R-squared, Adjusted R-squared, F-statistic, as follows.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the R-squared</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the adjusted R-squared</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>adj_r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>adj.r.squared</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the adjusted R-squared</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"R-squared:"</span>, r_squared, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R-squared: 0.8577974 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Adjusted R-squared:"</span>, adj_r_squared, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adjusted R-squared: 0.8304507 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the F-statistic and its associated p-value</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>f_statistic <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>fstatistic[<span class="dv">1</span>]</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the F-statistic and its associated p-value</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"F-statistic:"</span>, f_statistic, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F-statistic: 31.36754 </code></pre>
</div>
</div>
</section>
</section>
<section id="model-prediction-in-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-prediction-in-multiple-linear-regression">Model Prediction in Multiple Linear Regression</h2>
<ol type="1">
<li><p>In multiple linear regression, model prediction refers to the process of using the model to make predictions about the value of the dependent variable based on the values of the independent variables.</p></li>
<li><p>To make a <strong>prediction</strong> using a multiple linear regression model, we first need to specify the values of the independent variables for the observation we want to predict the dependent variable for.</p></li>
<li><p>Then, we use the coefficients estimated by the model to calculate the predicted value of the dependent variable.</p></li>
<li><p>Recall that the multiple linear regression equation can be written as: <span class="math inline">\(y = β_0 + β_1x_1 + β_2x_2 + … + β_px_p + ε\)</span>, where <span class="math inline">\(y\)</span> is the dependent variable, <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_p\)</span> are the independent variables, <span class="math inline">\(β_0\)</span> is the intercept, and <span class="math inline">\(β_1\)</span>, <span class="math inline">\(β_2\)</span>, …, <span class="math inline">\(β_p\)</span> are the coefficients for the independent variables. <span class="math inline">\(ε\)</span> represents the error term or residual, which represents the difference between the predicted value of <span class="math inline">\(y\)</span> and the actual value of <span class="math inline">\(y\)</span>.</p></li>
<li><p>To make a prediction using this equation, we would <strong>substitute the values of</strong> <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_p\)</span> into the equation and calculate the predicted value of <span class="math inline">\(y\)</span>.</p></li>
</ol>
<section id="prediction-in-multiple-linear-regression-in-r" class="level3">
<h3 class="anchored" data-anchor-id="prediction-in-multiple-linear-regression-in-r">Prediction in Multiple Linear Regression in R</h3>
<ol type="1">
<li>In R, we can make predictions using the fitted multiple linear regression model. For reference, let us summarize the model, we will be using for prediction.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the model summary to assess its performance and significance</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + hp + wt + cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2740 -1.0349 -0.3831  0.9810  5.4192 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 36.002405   2.130726  16.897 1.54e-15 ***
disp         0.004199   0.012917   0.325  0.74774    
hp          -0.023517   0.012216  -1.925  0.06523 .  
wt          -3.428626   1.055455  -3.248  0.00319 ** 
cyl6        -3.466011   1.462979  -2.369  0.02554 *  
cyl8        -3.753227   2.813996  -1.334  0.19385    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.482 on 26 degrees of freedom
Multiple R-squared:  0.8578,    Adjusted R-squared:  0.8305 
F-statistic: 31.37 on 5 and 26 DF,  p-value: 3.18e-10</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>We will create a new dataframe for the data to be used for the prediction. And then, we will run the <code>predict()</code> function.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions for a new car with weight of 2.5, </span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># displacement of 200, horsepower of 100, six cylinders</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>new_car <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wt =</span> <span class="fl">2.5</span>, <span class="at">disp =</span> <span class="dv">200</span>, <span class="at">hp =</span> <span class="dv">100</span>, <span class="at">cyl =</span> <span class="dv">6</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert cyl to a factor variable in the new data frame</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>new_car<span class="sc">$</span>cyl <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(new_car<span class="sc">$</span>cyl)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the prediction based on the model using the predict() function</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="at">newdata =</span> new_car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
22.45295 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li><p>In this example, we use <code>summary()</code> to review a multiple linear regression model. This model was estimated using the lm() function, with <code>mpg</code> as the dependent variable and <code>wt</code>, <code>disp</code>, <code>hp</code>, <code>cyl</code> as the independent variables.</p></li>
<li><p>The newdata argument specifies a data frame containing the values of the independent variables for a new car having weight of 2.5, displacement of 200, horsepower of 100, and 6 cylinders,</p></li>
<li><p>The output of the <code>predict()</code> function informs us that the predicted value of <code>mpg</code> for the new car, based on the fitted model, is 22.45295 mpg.</p></li>
</ol>
</section>
</section>
</section>
<section id="assumptions-made-in-ordinary-least-squares-ols-estimation" class="level1">
<h1>6 Assumptions made in Ordinary Least Squares (OLS) estimation</h1>
<p>OLS estimation makes several assumptions, and violating these assumptions can lead to biased or inefficient estimates of the regression coefficients. The following are the assumptions of OLS regression:</p>
<section id="linearity" class="level2">
<h2 class="anchored" data-anchor-id="linearity">1. Linearity:</h2>
<p>The relationship between the dependent variable and independent variables is linear. This means that the effect of a change in an independent variable on the dependent variable is constant.</p>
</section>
<section id="independence" class="level2">
<h2 class="anchored" data-anchor-id="independence">2. Independence:</h2>
<p>The observations in the dataset are independent of each other. In other words, the value of one observation does not depend on the value of another observation.</p>
</section>
<section id="homoscedasticity" class="level2">
<h2 class="anchored" data-anchor-id="homoscedasticity">3. Homoscedasticity:</h2>
<p>The variance of the error terms is constant across all values of the independent variables. This assumption is also known as the assumption of constant variance.</p>
</section>
<section id="normality" class="level2">
<h2 class="anchored" data-anchor-id="normality">4. Normality:</h2>
<p>The error terms are normally distributed with a mean of zero. This means that the distribution of the errors is symmetric and bell-shaped.</p>
</section>
<section id="no-multicollinearity" class="level2">
<h2 class="anchored" data-anchor-id="no-multicollinearity">5. No multicollinearity:</h2>
<p>There is no perfect linear relationship among the independent variables. In other words, the independent variables are not highly correlated with each other.</p>
</section>
<section id="no-outliers" class="level2">
<h2 class="anchored" data-anchor-id="no-outliers">6. No outliers:</h2>
<p>There are no extreme observations that are far away from the general pattern of the data. Such outliers can have a large effect on the estimates of the regression coefficients.</p>
<p>It is important to check for these assumptions before using OLS regression, and there are various methods to test for them. If any of these assumptions are violated, alternative methods such as robust regression or non-parametric regression may be more appropriate. [8]</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>[1]</p>
<p>Kutner, M. H., Nachtsheim, C. J., Neter, J., &amp; Li, W. (2005). Applied linear regression models (4th ed.). McGraw-Hill Irwin.</p>
<p>Montgomery, D. C., Peck, E. A., &amp; Vining, G. G. (2012). Introduction to linear regression analysis (5th ed.). Wiley.</p>
<p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2013). An introduction to statistical learning: With applications in R. Springer.</p>
<p>Agresti, A., &amp; Finlay, B. (2009). Statistical methods for the social sciences (4th ed.). Pearson.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2010). Multivariate data analysis (7th ed.). Pearson Education.</p>
<p>[2]</p>
<p>Berkowitz, E. N. (2010). Essentials of healthcare marketing (3rd ed.). Jones &amp; Bartlett Learning.</p>
<p>Jain, S. (2018). Marketing data science: Modeling techniques in predictive analytics with R and Python. Apress.</p>
<p>Kotler, P., &amp; Keller, K. L. (2016). Marketing management (15th ed.). Pearson.</p>
<p>Malhotra, N. K., &amp; Birks, D. F. (2006). Marketing research: An applied approach (3rd ed.). Pearson.</p>
<p>McCarthy, J. E., &amp; Perreault Jr, W. D. (2018). Basic marketing: A marketing strategy planning approach (20th ed.). McGraw-Hill.</p>
<p>[3]</p>
<p>Bodie, Z., Kane, A., &amp; Marcus, A. J. (2014). Investments (10th ed.). McGraw-Hill Education.</p>
<p>Altman, E. I. (1968). Financial ratios, discriminant analysis and the prediction of corporate bankruptcy. The Journal of Finance, 23(4), 589-609.</p>
<p>Markowitz, H. (1952). Portfolio selection. The Journal of Finance, 7(1), 77-91.</p>
<p>Hull, J. C. (2017). Options, futures, and other derivatives (10th ed.). Pearson Education.</p>
<p>Ross, S. A., Westerfield, R. W., Jordan, B. D., &amp; Roberts, G. S. (2018). Fundamentals of corporate finance (12th ed.). McGraw-Hill Education.</p>
<p>[4]</p>
<p>Aguinis, H. (2019). Performance management (3rd ed.). Pearson.</p>
<p>Saks, A. M. (2006). Antecedents and consequences of employee engagement. Journal of Managerial Psychology, 21(7), 600-619.</p>
<p>Schmitt, N., &amp; Chan, D. (1998). Personnel selection: A theoretical approach. Lawrence Erlbaum Associates.</p>
<p>Phillips, J. M., &amp; Gully, S. M. (2015). Strategic staffing (3rd ed.). Pearson.</p>
<p>Cox, T., &amp; Blake, S. (1991). Managing cultural diversity: Implications for organizational competitiveness. Academy of Management Executive, 5(3), 45-56.</p>
<p>[5]</p>
<p>Kutner, M. H., Nachtsheim, C. J., Neter, J., &amp; Li, W. (2005). Applied linear statistical models (5th ed.). McGraw-Hill.</p>
<p>Montgomery, D. C., Peck, E. A., &amp; Vining, G. G. (2012). Introduction to linear regression analysis (5th ed.). Wiley.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2019). Multivariate data analysis (8th ed.). Cengage Learning.</p>
<p>Draper, N. R., &amp; Smith, H. (1998). Applied regression analysis (3rd ed.). Wiley.</p>
<p>Field, A. (2013). Discovering statistics using IBM SPSS statistics (4th ed.). Sage.</p>
<p>[6]</p>
<p>Kutner, M. H., Nachtsheim, C. J., Neter, J., &amp; Li, W. (2005). Applied linear statistical models (5th ed.). McGraw-Hill.</p>
<p>Montgomery, D. C., Peck, E. A., &amp; Vining, G. G. (2012). Introduction to linear regression analysis (5th ed.). Wiley.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2019). Multivariate data analysis (8th ed.). Cengage Learning.</p>
<p>Draper, N. R., &amp; Smith, H. (1998). Applied regression analysis (3rd ed.). Wiley.</p>
<p>Field, A. (2013). Discovering statistics using IBM SPSS statistics (4th ed.). Sage.</p>
<p>[7]</p>
<p>R Core Team (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. <a href="http://www.r-project.org/"><strong>http://www.R-project.org/</strong></a></p>
<p>Venables, W. N., &amp; Ripley, B. D. (2002). Modern applied statistics with S (4th ed.). Springer.</p>
<p>Fox, J., &amp; Weisberg, S. (2019). An R companion to applied regression (3rd ed.). Sage.</p>
<p>Faraway, J. J. (2005). Linear models with R. Chapman and Hall/CRC.</p>
<p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2017). An introduction to statistical learning: With applications in R. Springer.</p>
<p>[8]</p>
<p>Bowerman, B. L., O’Connell, R. T., &amp; Koehler, A. B. (2018). Forecasting, time series, and regression: An applied approach (5th ed.). Cengage Learning.</p>
<p>Gujarati, D. N., &amp; Porter, D. C. (2009). Basic econometrics (5th ed.). McGraw-Hill.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2014). Multivariate data analysis (7th ed.). Pearson.</p>
<p>Kleinbaum, D. G., Kupper, L. L., Nizam, A., &amp; Muller, K. E. (2008). Applied regression analysis and other multivariable methods (4th ed.). Thomson Brooks/Cole.</p>
<p>Tabachnick, B. G., &amp; Fidell, L. S. (2013). Using multivariate statistics (6th ed.). Pearson.</p>
<p>Penn State University. (n.d.). Lesson 3: Multiple linear regression. Statistics 501: Regression Methods. Retrieved March 4, 2023, from <a href="https://online.stat.psu.edu/stat501/lesson/3"><strong>https://online.stat.psu.edu/stat501/lesson/3</strong></a></p>
<p>Freedman, D. A. (2009). Statistical models: Theory and practice. Cambridge University Press.</p>
<p>Gujarati, D. N. (2003). Basic econometrics (4th ed.). McGraw-Hill.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2014). Multivariate data analysis (7th ed.). Prentice Hall.</p>
<p>Wooldridge, J. M. (2013). Introductory econometrics: A modern approach (5th ed.). South-Western.</p>
<p>[9]</p>
<p>University of Illinois at Urbana-Champaign. (n.d.). Multiple linear regression. Statistics and Data Science Center. Retrieved March 4, 2023, from <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html"><strong>https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html</strong></a></p>
<p>R Core Team. (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. <a href="https://www.r-project.org/"><strong>https://www.R-project.org/</strong></a></p>
<p>Venables, W. N., Smith, D. M., &amp; R Development Core Team. (2008). An introduction to R. Network Theory Limited. <a href="http://cran.r-project.org/doc/manuals/R-intro.pdf"><strong>http://cran.r-project.org/doc/manuals/R-intro.pdf</strong></a></p>
<p>[10]</p>
<p>R Core Team. (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. https://www.R-project.org/</p>
<p>Wickham, H. (2016). ggplot2: Elegant graphics for data analysis. Springer-Verlag. https://ggplot2.tidyverse.org/</p>
<p>Fox, J. (2015). Applied regression analysis and generalized linear models (3rd ed.). Sage Publications.</p>
<p>Dalgaard, P. (2002). Introductory statistics with R (2nd ed.). Springer.</p>
<p>[11]</p>
<p>R Core Team. (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. https://www.R-project.org/</p>
<p>Fox, J. (2015). Applied regression analysis and generalized linear models (3rd ed.). Sage Publications.</p>
<p>Faraway, J. J. (2014). Linear models with R (2nd ed.). CRC Press.</p>
<p>Weisberg, S. (2005). Applied linear regression (3rd ed.). Wiley.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/">Sameer Mathur</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true">Aryeman Gupta Mathur</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>