<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analytics 102 -- Applied Statistics and Regression Using R – interaction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analytics 102 – Applied Statistics and Regression Using R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Sameer Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Aryeman Gupta Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/SameerMathur/DataAnalytics102" rel="" target="_blank"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Book’s Github</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08Interaction.html">Interactions</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/openscapes_hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01GettingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02ZTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Z Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03ChiSquareTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chi-Square Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04TTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07LinearRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08Interaction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Interactions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09LogLinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Log-Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10LogLog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Log-Log Regression</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="BookCover102.png" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#interactions" id="toc-interactions" class="nav-link active" data-scroll-target="#interactions">Interactions</a>
  <ul class="collapse">
  <li><a href="#business-applications-of-linear-regression-with-interaction" id="toc-business-applications-of-linear-regression-with-interaction" class="nav-link" data-scroll-target="#business-applications-of-linear-regression-with-interaction">Business Applications of Linear Regression with Interaction</a>
  <ul class="collapse">
  <li><a href="#marketing" id="toc-marketing" class="nav-link" data-scroll-target="#marketing">Marketing</a></li>
  <li><a href="#finance" id="toc-finance" class="nav-link" data-scroll-target="#finance">Finance</a></li>
  <li><a href="#organizational-behavior" id="toc-organizational-behavior" class="nav-link" data-scroll-target="#organizational-behavior">Organizational Behavior</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#linear-regression-with-interaction" id="toc-linear-regression-with-interaction" class="nav-link" data-scroll-target="#linear-regression-with-interaction">Linear Regression with Interaction</a>
  <ul class="collapse">
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#example-1-linear-regression-with-interaction-in-r" id="toc-example-1-linear-regression-with-interaction-in-r" class="nav-link" data-scroll-target="#example-1-linear-regression-with-interaction-in-r">Example 1: Linear Regression with Interaction in R</a></li>
  <li><a href="#example-2-linear-regression-with-interaction-in-r" id="toc-example-2-linear-regression-with-interaction-in-r" class="nav-link" data-scroll-target="#example-2-linear-regression-with-interaction-in-r">Example 2: Linear Regression with Interaction in R</a>
  <ul class="collapse">
  <li><a href="#comparison" id="toc-comparison" class="nav-link" data-scroll-target="#comparison">Comparison:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="08Interaction.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="interactions" class="level1">
<h1>Interactions</h1>
<p><em>July 26, 2023</em></p>
<p>A regression model with an interaction term allows us to examine how the relationship between the outcome variable and one predictor variable changes depending on the level of another predictor variable. It is a useful tool for modeling complex relationships between predictor variables and outcome variables.</p>
<p><strong>Example 1</strong></p>
<ol type="1">
<li><p>Suppose we are interested in the relationship between a person’s age (predictor variable 1) and their income (response variable), and we also like to determine whether the effect of age on income varies for men and women (predictor variable 2).</p></li>
<li><p>This relationship can be modeled using a linear regression model with an interaction term:</p>
<p><span class="math display">\[Income = β_0 + β_1(age) + β_2(gender) + β_3(age*gender) + ε\]</span></p></li>
<li><p>In this model, the <span class="math inline">\(β_1\)</span> coefficient represents the effect of age on income when gender is held constant, the <span class="math inline">\(β_2\)</span> coefficient represents the effect of gender on income when age is held constant, and the <span class="math inline">\(β_3\)</span> coefficient represents the effect of the interaction between age and gender on income.</p></li>
<li><p>The interaction term <span class="math inline">\(β_3\)</span> captures how the relationship between age and income differs for men and women.</p></li>
<li><p>If <span class="math inline">\(β_3\)</span> is positive, it means that the effect of age on income is stronger for one gender compared to the other, and if <span class="math inline">\(β_3\)</span> is negative, it means that the effect of age on income is weaker for one gender compared to the other.</p></li>
</ol>
<p><strong>Example 2</strong></p>
<ol type="1">
<li><p>Suppose we have a model that predicts a person’s Income based on their education level and years of experience.</p></li>
<li><p>In a model without an interaction term, we assume that the effect of education level on Income is constant across all levels of years of experience.</p>
<p><span class="math display">\[Income = β_0 + β_1(education) + β_2(experience) + ε\]</span></p></li>
<li><p>However, in reality, the effect of education level on Income may depend on the level of years of experience. For instance, the positive effect of education level on Income may be stronger for people with less experience than for people with more experience.</p></li>
<li><p>By including an interaction term in the model, we can allow the effect of one predictor variable (e.g., education level) to vary depending on the level of another predictor variable (e.g., years of experience).</p>
<p><span class="math display">\[Income = β_0 + β_1(education) + β_2(experience) + β_3(education*experience) + ε\]</span></p></li>
<li><p>This enables us to better capture the complexity of the relationship between the predictor variables and the outcome variable. [1]</p></li>
</ol>
<section id="business-applications-of-linear-regression-with-interaction" class="level2">
<h2 class="anchored" data-anchor-id="business-applications-of-linear-regression-with-interaction">Business Applications of Linear Regression with Interaction</h2>
<section id="marketing" class="level3">
<h3 class="anchored" data-anchor-id="marketing">Marketing</h3>
<ol type="1">
<li><p><strong>Segmentation analysis:</strong> Linear regression with interaction can be used to identify subgroups of customers with different preferences or behaviors. For example, a marketer may want to know how the relationship between a product attribute (e.g., price, quality, features) and customer satisfaction varies across different customer segments (e.g., age, gender, income, location). By estimating separate regression models for each segment and comparing the coefficients and fit statistics, the marketer can identify the key drivers of satisfaction for each segment and tailor the marketing mix accordingly.</p></li>
<li><p><strong>Product optimization:</strong> Linear regression with interaction can also be used to optimize the design and pricing of a product or service. By modeling the relationship between the product attributes and customer preferences, and incorporating the interaction effects, the marketer can identify the optimal levels of each attribute that maximize customer satisfaction or purchase intention. For example, a marketer may want to know how the price and quality of a product interact to affect the customer’s willingness to pay or repurchase. By estimating a regression model with an interaction term, the marketer can identify the price-quality tradeoff and the price point that maximizes the profit.</p></li>
<li><p><strong>Campaign targeting:</strong> Linear regression with interaction can also be used to improve the targeting and personalization of marketing campaigns. By modeling the relationship between the customer characteristics and response to different marketing messages, and incorporating the interaction effects, the marketer can identify the most effective messages for each customer segment. For example, a marketer may want to know how the age and gender of a customer interact to affect the response to a promotional offer. By estimating a regression model with an interaction term, the marketer can identify the customer segments that are most responsive to the offer and tailor the offer accordingly.</p></li>
<li><p><strong>Sales forecasting:</strong> Linear regression with interaction can also be used to forecast the sales of a product or service. By modeling the relationship between the sales and the explanatory variables, and incorporating the interaction effects, the marketer can identify the factors that influence the sales and predict the future demand. For example, a marketer may want to know how the advertising expenditure and the seasonality interact to affect the sales of a product. By estimating a regression model with an interaction term, the marketer can identify the optimal timing and allocation of the advertising budget and forecast the sales for different periods. [2]</p></li>
</ol>
</section>
<section id="finance" class="level3">
<h3 class="anchored" data-anchor-id="finance">Finance</h3>
<ol type="1">
<li><p><strong>Asset pricing models:</strong> Linear regression with interaction has been used to estimate asset pricing models, such as the Capital Asset Pricing Model (CAPM) and the Fama-French Three-Factor Model, that explain the variation in stock returns based on market risk, size, value, and other factors that interact with each other (Fama &amp; French, 1992; Sharpe, 1964).</p></li>
<li><p><strong>Risk management models:</strong> Linear regression with interaction has been used to model the joint distribution of multiple risk factors and to estimate Value-at-Risk (VaR) and Conditional Value-at-Risk (CVaR) measures that capture the tail risks and dependencies of portfolios and derivatives (Jorion, 2006; McNeil, Frey, &amp; Embrechts, 2015).</p></li>
<li><p><strong>Credit scoring models:</strong> Linear regression with interaction has been used to model the creditworthiness of borrowers based on their personal and financial characteristics and their interactions, and to estimate credit scores that predict the likelihood of default and the expected losses of loans and bonds (Altman &amp; Sabato, 2007; Thomas, Crook, &amp; Edelman, 2002).</p></li>
<li><p><strong>Event studies:</strong> Linear regression with interaction has been used to model the abnormal returns of stocks and bonds around corporate events, such as mergers, acquisitions, earnings announcements, and dividend changes, and to test the hypotheses of market efficiency, information asymmetry, and behavioral biases (Brown &amp; Warner, 1985; Fama, 1970; Lakonishok &amp; Vermaelen, 1986).</p></li>
<li><p><strong>Forecasting models:</strong> Linear regression with interaction has been used to forecast the future values of financial variables, such as stock prices, exchange rates, interest rates, and commodity prices, based on their past values, their interactions with other variables, and the market conditions that affect them (Elliott, Timmermann, &amp; Stock, 1996; West, 2006). [3]</p></li>
</ol>
</section>
<section id="organizational-behavior" class="level3">
<h3 class="anchored" data-anchor-id="organizational-behavior">Organizational Behavior</h3>
<ol type="1">
<li><p><strong>Organizational effectiveness:</strong> Linear regression with interaction can be used to study the interaction effects of different factors on organizational effectiveness. For example, a study by Aryee and Chen (2006) found that the relationship between organizational justice and organizational citizenship behavior was stronger among employees who had high levels of trust in their supervisors.</p></li>
<li><p><strong>Employee engagement:</strong> Linear regression with interaction can be used to study the interaction effects of different factors on employee engagement. For example, a study by Kim, Lee, and Chun (2015) found that the relationship between job autonomy and employee engagement was stronger among employees who had high levels of social support from their coworkers.</p></li>
<li><p><strong>Leadership effectiveness:</strong> Linear regression with interaction can be used to study the interaction effects of different leadership styles on leadership effectiveness. For example, a study by Howell and Avolio (1993) found that the relationship between transformational leadership and follower satisfaction was stronger among followers who had low levels of organizational structure. [4]</p></li>
</ol>
</section>
</section>
</section>
<section id="linear-regression-with-interaction" class="level1">
<h1>Linear Regression with Interaction</h1>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">Model</h2>
<ol type="1">
<li><p>A linear regression model with an interaction term is a statistical model that allows us to explore how the relationship between a predictor variable and a response variable changes depending on the level of another predictor variable.</p></li>
<li><p>In this type of model, the relationship between the response variable and each predictor variable is assumed to be linear.</p></li>
<li><p>The interaction term is included in the model to capture the effect of the interaction between two or more predictor variables on the response variable. The interaction term represents the product of the values of the two predictor variables that are being interacted with each other.</p></li>
<li><p>The regression equation for a model with an interaction term between two predictor variables can be expressed as follows:</p></li>
</ol>
<p><span class="math display">\[ Y = β_0 + β_1X_1 + β_2X_2 + β_3X_1X_2 + ε \]</span></p>
<ul>
<li><p><span class="math inline">\(Y\)</span> is the outcome variable.</p></li>
<li><p><span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are the two predictor variables.</p></li>
<li><p><span class="math inline">\(β_0\)</span> is the intercept coefficient, which represents the expected value of <span class="math inline">\(Y\)</span> when both <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are zero.</p></li>
<li><p><span class="math inline">\(β_1\)</span> is the coefficient for <span class="math inline">\(X_1\)</span>, which represents the change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X_1\)</span> when <span class="math inline">\(X_2\)</span> is held constant.</p></li>
<li><p><span class="math inline">\(β_2\)</span> is the coefficient for <span class="math inline">\(X2\)</span>, which represents the change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X_2\)</span> when <span class="math inline">\(X_1\)</span> is held constant.</p></li>
<li><p><span class="math inline">\(β_3\)</span> is the coefficient for the interaction term <span class="math inline">\(X_1X_2\)</span>, which represents the change in the effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X_2\)</span>. In other words, it represents the difference in the slope of the relationship between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(Y\)</span> at different levels of <span class="math inline">\(X_2\)</span>.</p></li>
<li><p><span class="math inline">\(ε\)</span> is the error term, which represents the random variation in <span class="math inline">\(Y\)</span> that is not explained by the predictor variables.</p></li>
</ul>
<ol start="5" type="1">
<li>The interaction term <span class="math inline">\(X_1X_2\)</span> captures the degree to which the relationship between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(Y\)</span> depends on the level of <span class="math inline">\(X_2\)</span>.</li>
</ol>
<ul>
<li><p>If <span class="math inline">\(β_3\)</span> is positive, it means that the effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> increases as <span class="math inline">\(X_2\)</span> increases.</p></li>
<li><p>If <span class="math inline">\(β_3\)</span> is negative, it means that the effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> decreases as <span class="math inline">\(X_2\)</span> increases.</p></li>
<li><p>If <span class="math inline">\(β_3\)</span> is zero, it means that there is no interaction between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, and the effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> is constant across all levels of <span class="math inline">\(X_2\)</span>.</p></li>
</ul>
<ol start="6" type="1">
<li>The regression equation can be used to estimate the expected value of <span class="math inline">\(Y\)</span> for a given combination of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, as well as to test the significance of the coefficients and the overall fit of the model.</li>
<li>The interpretation of the coefficients depends on the scale and measurement of the predictor and outcome variables, as well as the assumptions and limitations of the model. Therefore, it is important to carefully select and preprocess the data, specify and test the model assumptions, and interpret the results in the context of the research question and design. [5]</li>
</ol>
</section>
<section id="example-1-linear-regression-with-interaction-in-r" class="level2">
<h2 class="anchored" data-anchor-id="example-1-linear-regression-with-interaction-in-r">Example 1: Linear Regression with Interaction in R</h2>
<ol type="1">
<li>In this example, we will create a model to predict the miles per gallon (<strong><code>mpg</code></strong>) of a car based on its weight (<strong><code>wt</code></strong>) and whether it has an automatic (<strong><code>am=0</code></strong>) or manual transmission (<strong><code>am=1</code></strong>):</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load mtcars dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>am <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mtcars<span class="sc">$</span>am)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a linear regression model with interaction</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">*</span> am, <span class="at">data =</span> mtcars)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># print the model summary</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt * am, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6004 -1.5446 -0.5325  0.9012  6.0909 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  31.4161     3.0201  10.402 4.00e-11 ***
wt           -3.7859     0.7856  -4.819 4.55e-05 ***
am1          14.8784     4.2640   3.489  0.00162 ** 
wt:am1       -5.2984     1.4447  -3.667  0.00102 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.591 on 28 degrees of freedom
Multiple R-squared:  0.833, Adjusted R-squared:  0.8151 
F-statistic: 46.57 on 3 and 28 DF,  p-value: 5.209e-11</code></pre>
</div>
</div>
<ol start="2" type="1">
<li><p>We use the <strong><code>lm()</code></strong> function to create the regression model.</p></li>
<li><p>The <strong><code>*</code></strong> operator is used to include an interaction term between <strong><code>wt</code></strong> and <strong><code>am</code></strong>.</p></li>
<li><p>View the summary of the model by running <strong><code>summary(model)</code></strong>. This displays the coefficients for each variable in the model, as well as the interaction term.</p></li>
<li><p>The output shows the summary statistics for the <em>residuals</em> (i.e., the difference between the predicted values and the actual values of the response variable). The minimum and maximum values of the residuals are shown, as well as the first quartile (1Q), median, and third quartile (3Q) values.</p></li>
<li><p>It also displays the estimates of the regression coefficients, which represent the average change in the response variable (mpg) associated with a one-unit increase in the predictor variable, while holding all other variables constant.</p>
<ul>
<li><p>The intercept coefficient represents the predicted average mpg when weight is 0 and am is 0 (i.e., for automatic transmission). In this case, the intercept is 31.4161, meaning that the predicted average mpg for cars with automatic transmission and weight 0 is 31.4161.</p></li>
<li><p>The weight coefficient (wt) represents the predicted change in average mpg for a one-unit increase in weight, while holding am constant. In this case, the weight coefficient is -3.7859, meaning that for every one-unit increase in weight, the predicted average mpg decreases by 3.7859 units.</p></li>
<li><p>The am1 coefficient represents the difference in average mpg between cars with manual transmission (am=1) and automatic transmission (am=0), while holding weight constant. In this case, the am1 coefficient is 14.8784, meaning that the predicted average mpg for cars with manual transmission is 14.8784 units higher than the predicted average mpg for cars with automatic transmission, while holding weight constant.</p></li>
<li><p>The wt:am1 coefficient represents the interaction effect between weight and transmission type. In this case, the wt:am1 coefficient is -5.2984, meaning that the effect of weight on mpg depends on the transmission type, and the effect is significant (i.e., the p-value is less than 0.05).</p></li>
</ul></li>
<li><p>Residual standard error: This is an estimate of the standard deviation of the errors (residuals). In this case, the residual standard error is 2.591, meaning that the model’s predictions are typically off by about 2.591 mpg.</p></li>
<li><p>Multiple R-squared: 0.833, Adjusted R-squared: 0.8151</p></li>
</ol>
<p><strong>As a reference benchmark, we can run the model WITHOUT the interaction term.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert am to a factor variable</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>am <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mtcars<span class="sc">$</span>am)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional code to change the labels of the factor variable, if necessary</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># mtcars$am &lt;- factor(mtcars$am, labels = c("Automatic", "Manual"))</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear regression model without an interaction term</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>model0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> am, <span class="at">data =</span> mtcars)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary of the model</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + am, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5295 -2.3619 -0.1317  1.4025  6.8782 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.32155    3.05464  12.218 5.84e-13 ***
wt          -5.35281    0.78824  -6.791 1.87e-07 ***
am1         -0.02362    1.54565  -0.015    0.988    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.098 on 29 degrees of freedom
Multiple R-squared:  0.7528,    Adjusted R-squared:  0.7358 
F-statistic: 44.17 on 2 and 29 DF,  p-value: 1.579e-09</code></pre>
</div>
</div>
<ol type="1">
<li><p>As you can see, the model output now only has three coefficients, corresponding to the intercept, weight (wt), and transmission type (am).</p></li>
<li><p>The output shows that there is no significant difference in average mpg between cars with automatic and manual transmission types (p &gt; 0.05), after controlling for weight.</p></li>
<li><p>The other coefficients are interpreted in the same way as before.</p></li>
</ol>
<div style="page-break-after: always;"></div>
</section>
<section id="example-2-linear-regression-with-interaction-in-r" class="level2">
<h2 class="anchored" data-anchor-id="example-2-linear-regression-with-interaction-in-r">Example 2: Linear Regression with Interaction in R</h2>
<ol type="1">
<li><p>In this example, we will create a model to predict the miles per gallon (<strong><code>mpg</code></strong>) of a car based on its weight (<strong><code>wt</code></strong>) and the number of cylinders (<strong><code>cyl</code></strong>) in the engine.</p></li>
<li><p>Specifically, the number of cylinders in car engines are known to have either four, six or eight cylinders. Therefore, we will model cylinders (<strong><code>cyl</code></strong>) as a factor variables having three levels (<strong><code>cyl=4, cyl=6, cyl=8</code></strong>)</p></li>
<li><p>Here is the R code</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert cyl to a factor variable</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>cyl <span class="ot">&lt;-</span> <span class="fu">factor</span>(mtcars<span class="sc">$</span>cyl)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear regression model with interaction between wt and cyl</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">*</span> cyl, <span class="at">data =</span> mtcars)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary of the model</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt * cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.1513 -1.3798 -0.6389  1.4938  5.2523 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   39.571      3.194  12.389 2.06e-12 ***
wt            -5.647      1.359  -4.154 0.000313 ***
cyl6         -11.162      9.355  -1.193 0.243584    
cyl8         -15.703      4.839  -3.245 0.003223 ** 
wt:cyl6        2.867      3.117   0.920 0.366199    
wt:cyl8        3.455      1.627   2.123 0.043440 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.449 on 26 degrees of freedom
Multiple R-squared:  0.8616,    Adjusted R-squared:  0.8349 
F-statistic: 32.36 on 5 and 26 DF,  p-value: 2.258e-10</code></pre>
</div>
</div>
<p>In this model, we are regressing <strong><code>mpg</code></strong> on the main effects of <strong><code>wt</code></strong> and <strong><code>cyl</code></strong>, as well as the interaction term <strong><code>wt:cyl</code></strong>.</p>
<ul>
<li><p><strong><code>Call</code></strong>: This shows the call to the <strong><code>lm()</code></strong> function that was used to fit the linear regression model. The formula <strong><code>mpg ~ wt * cyl</code></strong> specifies that we are regressing <strong><code>mpg</code></strong> on the main effects of <strong><code>wt</code></strong> and <strong><code>cyl</code></strong>, as well as the interaction term <strong><code>wt:cyl</code></strong>. The <strong><code>data = mtcars</code></strong> argument specifies that the data should be taken from the <strong><code>mtcars</code></strong> dataset.</p></li>
<li><p><strong><code>Residuals</code></strong>: This shows the residuals of the model, which are the differences between the observed <strong><code>mpg</code></strong> values and the predicted <strong><code>mpg</code></strong> values from the model. The minimum residual is -4.1513, the maximum residual is 5.2523, and the median residual is -0.6389.</p></li>
<li><p><strong><code>Coefficients</code></strong>: This table shows the estimated coefficients of the linear regression model. The <strong><code>Estimate</code></strong> column shows the estimated effect of each variable on <strong><code>mpg</code></strong>, while the <strong><code>Std. Error</code></strong> column shows the standard error of each estimate. The <strong><code>t value</code></strong> column shows the t-value for each coefficient, which is calculated by dividing the estimated effect by its standard error.</p></li>
<li><p>The <strong><code>Pr(&gt;|t|)</code></strong> column shows the p-value for the t-test of each coefficient. If the p-value is less than 0.05, we can reject the null hypothesis that the coefficient is equal to zero, and conclude that the variable has a significant effect on <strong><code>mpg</code></strong>.</p></li>
<li><p><strong><code>(Intercept)</code></strong>: This is the intercept of the model, which represents the expected value of <strong><code>mpg</code></strong> when all other variables are zero.</p></li>
<li><p><strong><code>wt</code></strong>: This coefficient represents the effect of weight (wt) on <strong><code>mpg</code></strong>, holding the number of cylinders constant. The estimated effect is negative (-5.647), indicating that as weight increases, <strong><code>mpg</code></strong> tends to decrease.</p></li>
<li><p><strong><code>cyl6</code></strong> and <strong><code>cyl8</code></strong>: These coefficients represent the effect of the number of cylinders on <strong><code>mpg</code></strong>, holding weight constant. The coefficients indicate that there is no significant effect of having 6 cylinders on <strong><code>mpg</code></strong>, but having 8 cylinders is associated with a significant decrease in <strong><code>mpg</code></strong> (-15.703).</p></li>
<li><p><strong><code>wt:cyl6</code></strong> and <strong><code>wt:cyl8</code></strong>: These coefficients represent the effect of the interaction between weight and number of cylinders.</p></li>
<li><p>The intercept represents the expected value of <strong><code>mpg</code></strong> when all predictor variables are zero, which is not a meaningful interpretation in this case.</p></li>
<li><p>The coefficients for <strong><code>wt</code></strong>, <strong><code>cyl6</code></strong>, and <strong><code>cyl8</code></strong> represent the expected change in <strong><code>mpg</code></strong> associated with a one-unit increase in each of these variables, while holding all other variables constant.</p></li>
<li><p>The coefficients for the interaction terms <strong><code>wt:cyl6</code></strong> and <strong><code>wt:cyl8</code></strong> represent the expected change in the effect of <strong><code>wt</code></strong> on <strong><code>mpg</code></strong> associated with a one-unit increase in <strong><code>wt</code></strong>, for cars with 6 and 8 cylinders, respectively.</p></li>
<li><p>A coefficient that is significantly different from zero (indicated by a <strong><code>*</code></strong> or multiple <strong><code>*</code></strong> next to the p-value) suggests that the corresponding predictor variable has a significant effect on <strong><code>mpg</code></strong>.</p></li>
</ul>
<p><strong>As a reference benchmark, we can run the model without the interaction term.</strong></p>
<ol type="1">
<li>Here’s the R code for regressing <strong><code>mpg</code></strong> on <strong><code>wt</code></strong> and <strong><code>cyl</code></strong> (without an interaction term), after converting <strong><code>cyl</code></strong> to a factor variable using the mtcars dataset:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert cyl to a factor variable</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>cyl <span class="ot">&lt;-</span> <span class="fu">factor</span>(mtcars<span class="sc">$</span>cyl)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear regression model WITHOUT interaction between wt and cyl</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">*+</span> cyl, <span class="at">data =</span> mtcars)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary of the model</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt * +cyl, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.1513 -1.3798 -0.6389  1.4938  5.2523 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   39.571      3.194  12.389 2.06e-12 ***
wt            -5.647      1.359  -4.154 0.000313 ***
cyl6         -11.162      9.355  -1.193 0.243584    
cyl8         -15.703      4.839  -3.245 0.003223 ** 
wt:cyl6        2.867      3.117   0.920 0.366199    
wt:cyl8        3.455      1.627   2.123 0.043440 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.449 on 26 degrees of freedom
Multiple R-squared:  0.8616,    Adjusted R-squared:  0.8349 
F-statistic: 32.36 on 5 and 26 DF,  p-value: 2.258e-10</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>In this model, we have regressed <strong><code>mpg</code></strong> on <strong><code>wt</code></strong> and <strong><code>cyl</code></strong> without including an interaction term between them.</li>
<li>The output shows that both <strong><code>wt</code></strong> and <strong><code>cyl8</code></strong> have a statistically significant negative effect on <strong><code>mpg</code></strong>, while <strong><code>cyl6</code></strong> does not have a statistically significant effect at the 0.05 significance level.</li>
<li>Specifically, a one-unit increase in <strong><code>wt</code></strong> is associated with a 5.647 decrease in <strong><code>mpg</code></strong>, holding <strong><code>cyl</code></strong> constant. Similarly, cars with 8 cylinders have -15.703 lower <strong><code>mpg</code></strong> compared to cars with 4 cylinders, holding <strong><code>wt</code></strong> constant.</li>
<li>The model explains 83.49% of the variability in <strong><code>mpg</code></strong>, as indicated by the Adjusted R-squared value. The F-statistic of 32.36 and its associated p-value of 2.258e-10 suggest that the overall model is statistically significant.</li>
</ol>
<section id="comparison" class="level3">
<h3 class="anchored" data-anchor-id="comparison">Comparison:</h3>
<ol type="1">
<li><p>The first model (<strong><code>mpg ~ wt * cyl</code></strong>) includes an interaction term between <strong><code>wt</code></strong> and <strong><code>cyl</code></strong>, while the second model (<strong><code>mpg ~ wt + cyl</code></strong>) does not.</p></li>
<li><p>Comparing the two models, we can see that the first model includes an interaction term between <strong><code>wt</code></strong> and <strong><code>cyl</code></strong>, which allows the effect of <strong><code>wt</code></strong> on <strong><code>mpg</code></strong> to vary across different levels of <strong><code>cyl</code></strong>. Specifically, the model shows that the effect of <strong><code>wt</code></strong> on <strong><code>mpg</code></strong> is more negative for cars with 6 cylinders than for cars with 4 or 8 cylinders.</p></li>
<li><p>On the other hand, the second model assumes that the effect of <strong><code>wt</code></strong> on <strong><code>mpg</code></strong> is the same across all levels of <strong><code>cyl</code></strong>. This means that the second model is more parsimonious than the first model, as it has fewer parameters to estimate. However, it may not capture the full complexity of the relationship between <strong><code>wt</code></strong>, <strong><code>cyl</code></strong>, and <strong><code>mpg</code></strong>.</p></li>
<li><p>In terms of model fit, the first model (<strong><code>mpg ~ wt * cyl</code></strong>) has a slightly higher adjusted R-squared value (0.8349) compared to the second model’s adjusted R-squared (0.8349). This suggests that the first model explains a slightly larger proportion of the variability in <strong><code>mpg</code></strong> compared to the second model. However, the difference in adjusted R-squared values is relatively small, and both models have a high degree of explanatory power.</p></li>
</ol>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>[1]</p>
<p>Aiken, L. S., &amp; West, S. G. (1991). Multiple regression: Testing and interpreting interactions. Sage.</p>
<p>Cohen, J., Cohen, P., West, S. G., &amp; Aiken, L. S. (2003). Applied multiple regression/correlation analysis for the behavioral sciences. Routledge.</p>
<p>Hayes, A. F. (2018). Introduction to mediation, moderation, and conditional process analysis: A regression-based approach. Guilford Press.</p>
<p>Jaccard, J., &amp; Turrisi, R. (2003). Interaction effects in multiple regression. Sage.</p>
<p>Kline, R. B. (2015). Principles and practice of structural equation modeling. Guilford publications.</p>
<p>[2]</p>
<p>Aaker, D. A., Kumar, V., &amp; Day, G. S. (2007). Marketing research (9th ed.). John Wiley &amp; Sons.</p>
<p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2014). Multivariate data analysis (7th ed.). Prentice Hall.</p>
<p>Kumar, V., &amp; Reinartz, W. (2018). Customer relationship management: Concept, strategy, and tools (3rd ed.). Springer.</p>
<p>Lewis-Beck, M. S. (2016). Applied regression: An introduction (3rd ed.). Sage.</p>
<p>Malhotra, N. K., &amp; Birks, D. F. (2017). Marketing research: An applied approach (5th ed.). Pearson.</p>
<p>Srivastava, R. K., Shervani, T. A., &amp; Fahey, L. (1998). Market-based assets and shareholder value: A framework for analysis. Journal of Marketing, 62(1), 2-18.</p>
<p>[3]</p>
<p>Fama, E. F., &amp; French, K. R. (1992). The cross-section of expected stock returns. The Journal of Finance, 47(2), 427-465.</p>
<p>Jorion, P. (2006). Value at risk: The new benchmark for controlling market risk. McGraw-Hill.</p>
<p>Lakonishok, J., &amp; Vermaelen, T. (1986). Tax-induced trading around ex-dividend days. The Journal of Finance, 41(4), 857-872.</p>
<p>McNeil, A. J., Frey, R., &amp; Embrechts, P. (2015). Quantitative risk management: Concepts, techniques and tools. Princeton University Press.</p>
<p>Sharpe, W. F. (1964). Capital asset prices: A theory of market equilibrium under conditions of risk. The Journal of Finance, 19(3), 425-442.</p>
<p>Thomas, L. C., Crook, J. N., &amp; Edelman, D. B. (2002). Credit scoring and its applications (2nd ed.). SIAM.</p>
<p>West, K. D. (2006). Forecast evaluation. In G. Elliott, C. W. J. Granger, &amp; A. G. Timmermann (Eds.), Handbook of economic forecasting (Vol. 1, pp.&nbsp;99-134). Elsevier.</p>
<p>[4]</p>
<p>Aryee, S., &amp; Chen, Z. X. (2006). Leader-member exchange in a Chinese context: Antecedents, the mediating role of psychological empowerment and outcomes. Journal of Business Research, 59(7), 793-801.</p>
<p>Howell, J. M., &amp; Avolio, B. J. (1993). Transformational leadership, transactional leadership, locus of control, and support for innovation: Key predictors of consolidated-business-unit performance. Journal of Applied Psychology, 78(6), 891-902.</p>
<p>Kim, W. G., Lee, D., &amp; Chun, C. H. (2015). The effect of job autonomy and social support on job satisfaction and organizational commitment: The case of Korean employees. Journal of Applied Business Research (JABR), 31(3), 829-844.</p>
<p>[5]</p>
<p>Aiken, L. S., &amp; West, S. G. (1991). Multiple regression: Testing and interpreting interactions. Sage.</p>
<p>Cohen, J., Cohen, P., West, S. G., &amp; Aiken, L. S. (2003). Applied multiple regression/correlation analysis for the behavioral sciences. Routledge.</p>
<p>Kutner, M. H., Nachtsheim, C. J., Neter, J., &amp; Li, W. (2004). Applied linear regression models. McGraw-Hill Irwin.</p>
<p>Montgomery, D. C., Peck, E. A., &amp; Vining, G. G. (2012). Introduction to linear regression analysis. John Wiley &amp; Sons.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/">Sameer Mathur</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true">Aryeman Gupta Mathur</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>